/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.EventGraph.Basic

/-! # Cut-based execution of event graphs

Configurations store initial values separately from optional event outputs.
Their invariant says exactly that an output is present when its event belongs
to the completed cut. Completion history is chronological and retains the
supplied dependent action, including a resolving `true` whose checked result
is failure.
-/

noncomputable section

namespace Vegas

open GameTheory.Math.Probability

variable {Player : Type}
variable {L : IExpr} [R : IExpr.ResultTypes L]

namespace EventGraph

/-- A structurally coherent execution configuration. The fields tie store and
history domains exactly to the cut; semantic reachability is generated by
`initial` and `step`, rather than assumed by this carrier. -/
structure Config (graph : Vegas.EventGraph Player L) where
  inputs : graph.Inputs
  cut : graph.order.Cut
  outputs : (event : graph.EventId) → Option (graph.outputLayout event).Value
  output_available : ∀ event, (outputs event).isSome ↔ event ∈ cut.completed
  history : List graph.Completion
  history_nodup : (history.map Completion.event).Nodup
  history_exact : ∀ event, event ∈ history.map Completion.event ↔ event ∈ cut.completed

namespace Config

variable {graph : Vegas.EventGraph Player L}

instance (cut : graph.order.Cut) : Decidable cut.Terminal := by
  unfold EventOrder.Cut.Terminal
  infer_instance

/-- The initial configuration for one separately supplied input environment. -/
def initial (inputs : graph.Inputs) : graph.Config where
  inputs := inputs
  cut := EventOrder.Cut.empty graph.order
  outputs := fun _ => none
  output_available := by simp [EventOrder.Cut.empty]
  history := []
  history_nodup := by simp
  history_exact := by simp [EventOrder.Cut.empty]

/-- The combined typed partial store seen by node code. Inputs are always
available; event outputs are available exactly at completed events. -/
def store (config : graph.Config) : Store graph.layout
  | .inl input => some (config.inputs input)
  | .inr event => config.outputs event

@[simp] theorem store_input (config : graph.Config) (input : graph.InputId) :
    config.store (.inl input) = some (config.inputs input) := rfl

@[simp] theorem store_output (config : graph.Config) (event : graph.EventId) :
    config.store (.inr event) = config.outputs event := rfl

/-- Every declared read of a ready event is present in the exact store. -/
theorem read_available (config : graph.Config) {event : graph.EventId}
    (ready : config.cut.Ready event) {field : graph.Field}
    (read : field ∈ (graph.nodes event).readFields) :
    (config.store field).isSome := by
  cases field with
  | inl input => simp [store]
  | inr producer =>
      rw [store_output, config.output_available]
      exact ready.2 (graph.reads_available event (.inr producer) read)

/-- At a terminal cut every field in the combined typed store is available. -/
theorem store_available_of_terminal (config : graph.Config)
    (terminal : config.cut.Terminal) (field : graph.Field) :
    (config.store field).isSome = true := by
  cases field with
  | inl input => simp [store]
  | inr event =>
      rw [store_output, config.output_available]
      rw [EventOrder.Cut.Terminal] at terminal
      simp [terminal]

/-- Read the complete typed field environment without defaults. -/
def outcome (config : graph.Config) (terminal : config.cut.Terminal) : graph.Outcome :=
  fun field => (config.store field).get (config.store_available_of_terminal terminal field)

/-- Evaluate the graph's retained terminal payoff expressions. This is a
distinguished semantic projection of the complete outcome, not a definition of
players' utilities. -/
def terminalPayoffs (config : graph.Config) (terminal : config.cut.Terminal) :
    List (Player × L.Val L.int) :=
  graph.payoffs.map fun payoff =>
    ⟨payoff.1, (payoff.2.eval? config.store).get
      (PublicExpr.eval?_isSome payoff.2 config.store
        (fun field _ => config.store_available_of_terminal terminal field))⟩

/-- Partial terminal decoder. `none` means execution is unfinished, never that
a completed event stored failure: failure is an ordinary `PublicationResult`. -/
def outcome? (config : graph.Config) : Option graph.Outcome :=
  if terminal : config.cut.Terminal then some (config.outcome terminal) else none

@[simp] theorem outcome?_isSome (config : graph.Config) :
    config.outcome?.isSome = true ↔ config.cut.Terminal := by
  unfold outcome?
  split <;> simp_all

/-- Store one event output, extend the cut, and append the original action to
the chronological history. -/
def complete (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (value : (graph.outputLayout event).Value) : graph.Config where
  inputs := config.inputs
  cut := config.cut.complete event ready
  outputs := Function.update config.outputs event (some value)
  output_available := by
    intro query
    by_cases same : query = event
    · subst query
      simp [Function.update]
    · simp only [Function.update, same]
      simpa [EventOrder.Cut.mem_complete, same] using config.output_available query
  history := config.history ++ [⟨event, action⟩]
  history_nodup := by
    rw [List.map_append]
    simp only [List.map_cons, List.map_nil, List.nodup_append]
    refine ⟨config.history_nodup, by simp, ?_⟩
    intro prior priorMem appended appendedMem
    have appendedEq : appended = event := by simpa using appendedMem
    subst appended
    intro priorEq
    subst prior
    exact ready.1 ((config.history_exact event).mp priorMem)
  history_exact := by
    intro query
    simp only [List.map_append, List.map_cons, List.map_nil,
      List.mem_append, List.mem_singleton, EventOrder.Cut.mem_complete]
    rw [config.history_exact]
    tauto

@[simp] theorem complete_cut (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (value : (graph.outputLayout event).Value) :
    (config.complete event ready action value).cut = config.cut.complete event ready := rfl

@[simp] theorem complete_history (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (value : (graph.outputLayout event).Value) :
    (config.complete event ready action value).history =
      config.history ++ [⟨event, action⟩] := rfl

/-- The completed event stores precisely the evaluator output supplied to
`complete`; in particular, bind results retain their original value. -/
@[simp] theorem complete_output_same (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (value : (graph.outputLayout event).Value) :
    (config.complete event ready action value).outputs event = some value := by
  simp [complete, Function.update]

/-- Completing one event cannot rewrite any distinct event output. -/
theorem complete_output_of_ne (config : graph.Config) (event query : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (value : (graph.outputLayout event).Value) (different : query ≠ event) :
    (config.complete event ready action value).outputs query = config.outputs query := by
  simp [complete, Function.update, different]

/-- Execute any selected ready event. Chance remains in the returned finite
law rather than being replaced by an external choice. -/
def step (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event) :
    FinDist graph.Config :=
  ((graph.nodes event).eval? action config.store).get
    (EventCode.eval?_isSome_of_reads (graph.nodes event) action config.store
      (fun _ read => config.read_available ready read)) |>.map
        (config.complete event ready action)

/-- A local evaluator law determines the actual configuration transition.
The readiness proof supplies availability; it does not change the law. -/
theorem step_eq_map_of_eval (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (law : FinDist (graph.outputLayout event).Value)
    (evaluates : (graph.nodes event).eval? action config.store = some law) :
    config.step event ready action = law.map (config.complete event ready action) := by
  unfold step
  simp only [evaluates, Option.get_some]

/-- A compiler may identify an event's output kind through a typed embedding.
Transporting its code, action, and output along that same equality preserves
the ordinary graph transition. -/
theorem step_eq_map_of_code (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) {output : EventField Player L}
    (outputEq : graph.outputLayout event = output)
    (code : EventCode graph.layout output)
    (codeEq : cast (congrArg (EventCode graph.layout) outputEq) (graph.nodes event) = code)
    (action : output.Action) (law : FinDist output.Value)
    (evaluates : code.eval? action config.store = some law) :
    config.step event ready (cast (congrArg EventField.Action outputEq.symm) action) =
      law.map (fun value => config.complete event ready
        (cast (congrArg EventField.Action outputEq.symm) action)
        (cast (congrArg EventField.Value outputEq.symm) value)) := by
  cases outputEq
  subst code
  exact config.step_eq_map_of_eval event ready action law evaluates

@[simp] theorem step_cut (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (next : graph.Config) (member : next ∈ (config.step event ready action).support) :
    next.cut = config.cut.complete event ready := by
  rw [step, FinDist.support_map] at member
  obtain ⟨value, _, rfl⟩ := member
  rfl

/-- A strategic event has exactly one successor once its action is fixed. -/
theorem step_eq_pure_of_actor (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (owner : Player) (owned : (graph.nodes event).actor = some owner)
    (next : graph.Config) (member : next ∈ (config.step event ready action).support) :
    config.step event ready action = FinDist.pure next := by
  obtain ⟨value, evaluates⟩ := (graph.nodes event).eval?_eq_pure_of_actor owner owned
    action config.store (fun _ read => config.read_available ready read)
  have law := config.step_eq_map_of_eval event ready action (FinDist.pure value) evaluates
  rw [FinDist.map_pure] at law
  rw [law, FinDist.mem_support_pure] at member
  exact law.trans (congrArg FinDist.pure member.symm)

@[simp] theorem step_history (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (next : graph.Config) (member : next ∈ (config.step event ready action).support) :
    next.history = config.history ++ [⟨event, action⟩] := by
  rw [step, FinDist.support_map] at member
  obtain ⟨value, _, rfl⟩ := member
  rfl

/-- A graph completion writes only its previously unavailable output field. -/
theorem step_store_of_some (config next : graph.Config)
    (event : graph.EventId) (ready : config.cut.Ready event) (action : graph.Action event)
    (member : next ∈ (config.step event ready action).support)
    (field : graph.Field) (value : (graph.layout field).Value)
    (stored : config.store field = some value) : next.store field = some value := by
  rw [step, FinDist.support_map] at member
  obtain ⟨output, _, rfl⟩ := member
  cases field with
  | inl input => exact stored
  | inr query =>
      have different : query ≠ event := by
        intro same
        subst query
        have present : (config.outputs event).isSome := by
          change config.outputs event = some value at stored
          simp [stored]
        exact ready.1 ((config.output_available event).mp present)
      exact (config.complete_output_of_ne event query ready action output different).trans stored

/-- Semantic reachability from one concrete input environment. This is the
premise under which chronological-history properties should be consumed. -/
inductive Reachable (inputs : graph.Inputs) : graph.Config → Prop
  | initial : Reachable inputs (initial inputs)
  | step {config : graph.Config} (_ : Reachable inputs config)
      (event : graph.EventId) (ready : config.cut.Ready event)
      (action : graph.Action event) (next : graph.Config)
      (_ : next ∈ (config.step event ready action).support) : Reachable inputs next

/-- In a reachable history every direct predecessor occurs strictly before
the completed event. No such claim is made for an arbitrary raw `Config`. -/
theorem Reachable.predecessor_idxOf_lt {inputs : graph.Inputs} {config : graph.Config}
    (reachable : Reachable inputs config) (event : graph.EventId)
    (completed : event ∈ config.cut.completed) (predecessor : graph.EventId)
    (isPredecessor : predecessor ∈ graph.order.predecessors event) :
    (config.history.map Completion.event).idxOf predecessor <
      (config.history.map Completion.event).idxOf event := by
  induction reachable with
  | initial =>
      change event ∈ (∅ : Finset graph.EventId) at completed
      simp at completed
  | step priorReachable newEvent ready action next supported ih =>
      rename_i priorConfig
      have cutEq := Config.step_cut _ _ ready action next supported
      have historyEq := Config.step_history _ _ ready action next supported
      rw [cutEq, EventOrder.Cut.mem_complete] at completed
      rw [historyEq, List.map_append]
      simp only [List.map_cons, List.map_nil]
      rcases completed with rfl | completedBefore
      · have predecessorBefore : predecessor ∈
            priorConfig.cut.completed := ready.2 isPredecessor
        have predecessorMem : predecessor ∈
            priorConfig.history.map Completion.event :=
          (priorConfig.history_exact predecessor).2 predecessorBefore
        have eventNotMem : event ∉
            priorConfig.history.map Completion.event := by
          intro member
          exact ready.1 ((priorConfig.history_exact event).1 member)
        rw [List.idxOf_append_of_mem predecessorMem,
          List.idxOf_append_of_notMem eventNotMem]
        simp
        simpa using List.idxOf_lt_length_of_mem predecessorMem
      · have predecessorCompleted :=
          priorConfig.cut.predecessor_closed completedBefore isPredecessor
        have eventMem : event ∈ priorConfig.history.map Completion.event :=
          (priorConfig.history_exact event).2 completedBefore
        have predecessorMem : predecessor ∈
            priorConfig.history.map Completion.event :=
          (priorConfig.history_exact predecessor).2 predecessorCompleted
        rw [List.idxOf_append_of_mem predecessorMem, List.idxOf_append_of_mem eventMem]
        exact ih completedBefore

end Config

/-- A causal execution plan may randomize and adapt its next ready event and
action to the entire current semantic configuration. It cannot select an unready event.
Public/native schedulers later restrict which parts of this configuration are
observable; this ideal runner does not assume such a projection. -/
abbrev EventPlan (graph : Vegas.EventGraph Player L) :=
  (config : graph.Config) → ¬ config.cut.Terminal →
    FinDist (Σ selected : {event : graph.EventId // config.cut.Ready event},
      graph.Action selected.1)

/-- Execute at most `fuel` events according to an adaptive causal plan. -/
def runPlan (graph : Vegas.EventGraph Player L) (plan : graph.EventPlan) :
    Nat → graph.Config → FinDist graph.Config
  | 0, config => FinDist.pure config
  | fuel + 1, config =>
      if terminal : config.cut.Terminal then
        FinDist.pure config
      else
        (plan config terminal).bind fun choice =>
          (config.step choice.1.1 choice.1.2 choice.2).bind
            (graph.runPlan plan fuel)

/-- The complete finite runner. The event count is a sufficient fuel bound
because every step adds exactly one previously unfinished event to the cut. -/
def run (graph : Vegas.EventGraph Player L) (inputs : graph.Inputs) (plan : graph.EventPlan) :
    FinDist graph.Config :=
  graph.runPlan plan graph.order.eventCount (Config.initial inputs)

/-- The finite plan runner preserves semantic reachability from fixed inputs. -/
theorem runPlan_reachable (graph : Vegas.EventGraph Player L) (plan : graph.EventPlan)
    (inputs : graph.Inputs) : ∀ fuel config next,
    Config.Reachable inputs config →
    next ∈ (graph.runPlan plan fuel config).support →
    Config.Reachable inputs next := by
  intro fuel
  induction fuel with
  | zero =>
      intro config next reachable member
      have nextEq : next = config := by simpa [runPlan] using member
      exact nextEq ▸ reachable
  | succ fuel ih =>
      intro config next reachable member
      by_cases terminal : config.cut.Terminal
      · have nextEq : next = config := by simpa [runPlan, terminal] using member
        exact nextEq ▸ reachable
      · rw [runPlan, dite_eq_right terminal, FinDist.support_bind] at member
        simp only [Set.mem_iUnion] at member
        obtain ⟨choice, _, restMem⟩ := member
        rw [FinDist.support_bind] at restMem
        simp only [Set.mem_iUnion] at restMem
        obtain ⟨intermediate, intermediateMem, nextMem⟩ := restMem
        have intermediateReachable : Config.Reachable inputs intermediate :=
          .step reachable choice.1.1 choice.1.2 choice.2 intermediate intermediateMem
        exact ih intermediate next intermediateReachable nextMem

/-- Every supported full-run result is reachable from the supplied inputs. -/
theorem run_reachable (graph : Vegas.EventGraph Player L) (inputs : graph.Inputs)
    (plan : graph.EventPlan) (next : graph.Config)
    (member : next ∈ (graph.run inputs plan).support) :
    Config.Reachable inputs next := by
  exact graph.runPlan_reachable plan inputs graph.order.eventCount
    (Config.initial inputs) next .initial member

/-- Number of events not yet completed. -/
def Config.remaining {graph : Vegas.EventGraph Player L} (config : graph.Config) : Nat :=
  graph.order.eventCount - config.cut.completed.card

theorem Config.terminal_iff_remaining_zero {graph : Vegas.EventGraph Player L}
    (config : graph.Config) : config.cut.Terminal ↔ config.remaining = 0 := by
  constructor
  · intro terminal
    rw [EventOrder.Cut.Terminal] at terminal
    simp [Config.remaining, terminal]
  · intro remaining
    unfold EventOrder.Cut.Terminal
    apply Finset.eq_of_subset_of_card_le (Finset.subset_univ _)
    have cardLe : config.cut.completed.card ≤ graph.order.eventCount := by
      simpa using Finset.card_le_card (Finset.subset_univ config.cut.completed)
    have cardEq : config.cut.completed.card = graph.order.eventCount := by
      unfold Config.remaining at remaining
      omega
    simp [cardEq]

/-- Every supported step consumes exactly one remaining event. -/
theorem Config.remaining_step {graph : Vegas.EventGraph Player L}
    (config : graph.Config) (event : graph.EventId)
    (ready : config.cut.Ready event) (action : graph.Action event)
    (next : graph.Config) (member : next ∈ (config.step event ready action).support) :
    next.remaining + 1 = config.remaining := by
  rw [Config.remaining, Config.remaining, config.step_cut event ready action next member,
    EventOrder.Cut.card_complete]
  have cardLe : config.cut.completed.card < graph.order.eventCount := by
    have eventInUniv : event ∈ (Finset.univ : Finset graph.EventId) := Finset.mem_univ _
    have proper : config.cut.completed ⊂ (Finset.univ : Finset graph.EventId) :=
      Finset.ssubset_iff_subset_ne.mpr ⟨Finset.subset_univ _, by
        intro equal
        exact ready.1 (equal.symm ▸ eventInUniv)⟩
    simpa using Finset.card_lt_card proper
  omega

/-- Enough fuel completes every supported execution, independently of which
ready events and actions the randomized plan selects. -/
theorem runPlan_terminal (graph : Vegas.EventGraph Player L) (plan : graph.EventPlan) :
    ∀ fuel config next, config.remaining ≤ fuel →
      next ∈ (graph.runPlan plan fuel config).support → next.cut.Terminal := by
  intro fuel
  induction fuel with
  | zero =>
      intro config next enough member
      have zero : config.remaining = 0 := by omega
      have terminal := (config.terminal_iff_remaining_zero).2 zero
      have nextEq : next = config := by simpa [runPlan] using member
      subst next
      exact terminal
  | succ fuel ih =>
      intro config next enough member
      by_cases terminal : config.cut.Terminal
      · have nextEq : next = config := by simpa [runPlan, terminal] using member
        subst next
        exact terminal
      · rw [runPlan, dite_eq_right terminal, FinDist.support_bind] at member
        simp only [Set.mem_iUnion] at member
        obtain ⟨choice, _, restMem⟩ := member
        rw [FinDist.support_bind] at restMem
        simp only [Set.mem_iUnion] at restMem
        obtain ⟨intermediate, intermediateMem, nextMem⟩ := restMem
        have decreased := config.remaining_step choice.1.1 choice.1.2 choice.2
          intermediate intermediateMem
        apply ih intermediate next (by omega) nextMem

/-- The full event-count runner terminates on every supported result. -/
theorem run_terminal (graph : Vegas.EventGraph Player L) (inputs : graph.Inputs)
    (plan : graph.EventPlan) (next : graph.Config)
    (member : next ∈ (graph.run inputs plan).support) : next.cut.Terminal := by
  apply graph.runPlan_terminal plan graph.order.eventCount (Config.initial inputs) next
  · simp [Config.remaining, Config.initial]
  · exact member

end EventGraph

end Vegas
