/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.EventGraph.SchedulerReplay

/-! # Actual-run laws for deterministic scheduler replay -/

noncomputable section

namespace Vegas.EventGraph

open GameTheory.Math.Probability

variable {Player : Type} [DecidableEq Player]
variable {L : IExpr} [R : IExpr.ResultTypes L]
variable {graph : Vegas.EventGraph Player L}

/-- Reachability generated by the ordinary graph step and one fixed pure
public scheduler.  Player actions and node chance remain unrestricted. -/
inductive SchedulerReachable (scheduler : graph.DeterministicPublicScheduler)
    (inputs : graph.Inputs) : graph.Config → Prop
  | initial : SchedulerReachable scheduler inputs (Config.initial inputs)
  | step {config : graph.Config} (_ : SchedulerReachable scheduler inputs config)
      (notTerminal : ¬ config.cut.Terminal) (event : graph.EventId)
      (selected : (scheduler (graph.publicObserve config) config.cut.enabled
        (enabled_nonempty_of_not_terminal config notTerminal)).1 = event)
      (ready : config.cut.Ready event) (action : graph.Action event)
      (next : graph.Config) (_ : next ∈ (config.step event ready action).support) :
      SchedulerReachable scheduler inputs next

/-- Every supported run of the existing policy plan under a pure scheduler is
scheduler-reachable.  This is an invariant of `runPlan`, not another runner. -/
theorem runPlan_schedulerReachable
    (scheduler : graph.DeterministicPublicScheduler)
    (profile : graph.BehavioralProfile) (inputs : graph.Inputs) :
    ∀ fuel config next,
      graph.SchedulerReachable scheduler inputs config →
      next ∈ (graph.runPlan
        (graph.policyPlan profile scheduler.toPublic) fuel config).support →
      graph.SchedulerReachable scheduler inputs next := by
  intro fuel
  induction fuel with
  | zero =>
      intro config next reachable member
      have same : next = config := by simpa [runPlan] using member
      exact same ▸ reachable
  | succ fuel ih =>
      intro config next reachable member
      by_cases terminal : config.cut.Terminal
      · have same : next = config := by simpa [runPlan, terminal] using member
        exact same ▸ reachable
      · rw [runPlan, dite_eq_right terminal, FinDist.support_bind] at member
        simp only [Set.mem_iUnion] at member
        obtain ⟨choice, choiceMem, restMem⟩ := member
        rw [FinDist.support_bind] at restMem
        simp only [Set.mem_iUnion] at restMem
        obtain ⟨intermediate, intermediateMem, nextMem⟩ := restMem
        have selected :
            (scheduler (graph.publicObserve config) config.cut.enabled
              (enabled_nonempty_of_not_terminal config terminal)).1 = choice.1.1 := by
          unfold policyPlan DeterministicPublicScheduler.toPublic at choiceMem
          simp only [FinDist.pure_bind] at choiceMem
          split at choiceMem <;> rename_i ownerEq
          · rw [FinDist.support_map] at choiceMem
            obtain ⟨action, _, rfl⟩ := choiceMem
            rfl
          · simpa using congrArg (fun selected => selected.1.1)
              (FinDist.mem_support_pure.mp choiceMem).symm
        have intermediateReachable : graph.SchedulerReachable scheduler inputs intermediate :=
          .step reachable terminal choice.1.1 selected choice.1.2 choice.2
            intermediate intermediateMem
        exact ih intermediate next intermediateReachable nextMem

omit [DecidableEq Player] in
/-- A supported graph step preserves every field that was already available. -/
theorem store_eq_of_step_of_available (config : graph.Config)
    (event : graph.EventId) (ready : config.cut.Ready event)
    (action : graph.Action event) (next : graph.Config)
    (member : next ∈ (config.step event ready action).support)
    (field : graph.Field) (available : graph.FieldAvailable config.cut field) :
    next.store field = config.store field := by
  rw [Config.step, FinDist.support_map] at member
  obtain ⟨value, _, rfl⟩ := member
  cases field with
  | inl input => rfl
  | inr producer =>
      have completed : producer ∈ config.cut.completed := available
      have different : producer ≠ event := by
        intro same
        subst producer
        exact ready.1 completed
      simp [Config.store, Config.complete, Function.update, different]

omit [DecidableEq Player] in
/-- Masking a later store that agrees on all currently available fields
reconstructs the current public store exactly. -/
theorem replayPublicStore_eq_publicStore (config : graph.Config)
    (later : EventGraph.Store graph.layout)
    (agree : ∀ field, graph.FieldAvailable config.cut field →
      graph.fieldPublic field → later field = config.store field) :
    graph.replayPublicStore config.cut later = graph.publicStore config.store := by
  funext field
  by_cases available : graph.FieldAvailable config.cut field
  · simp only [replayPublicStore, ite_eq_left available]
    by_cases isPublic : graph.fieldPublic field
    · simp [publicStore, isPublic, agree field available isPublic]
    · simp [publicStore, isPublic]
  · have absent : config.store field = none :=
      Option.not_isSome_iff_eq_none.mp (by
        simpa [Config.store_isSome_iff_fieldAvailable] using available)
    simp [replayPublicStore, available, publicStore, absent]

omit [DecidableEq Player] in
/-- Scheduler reachability is the exact invariant needed by replay: a later
immutable store lets replay traverse the generated history and resume at the
reached cut. -/
theorem SchedulerReachable.replayPrefixAux_suffix
    {scheduler : graph.DeterministicPublicScheduler} {inputs : graph.Inputs}
    {config : graph.Config} (reachable : graph.SchedulerReachable scheduler inputs config)
    (later : EventGraph.Store graph.layout)
    (agree : ∀ field, graph.FieldAvailable config.cut field →
      graph.fieldPublic field → later field = config.store field)
    (target : graph.EventId) (unfinished : target ∉ config.cut.completed)
    (fuel : Nat) :
    graph.replayPrefixAux scheduler target later
        ((config.history.map Completion.event).length + fuel)
        (EventOrder.Cut.empty graph.order) [] =
      graph.replayPrefixAux scheduler target later fuel config.cut
        (config.history.map Completion.event) := by
  induction reachable generalizing fuel with
  | initial => simp [Config.initial]
  | @step prior priorReachable notTerminal event selected ready action next member ih =>
      have nextCut : next.cut = prior.cut.complete event ready :=
        prior.step_cut event ready action next member
      have nextHistory : next.history = prior.history ++ [⟨event, action⟩] :=
        prior.step_history event ready action next member
      have targetNe : event ≠ target := by
        intro same
        apply unfinished
        rw [nextCut]
        simp [same]
      have targetPrior : target ∉ prior.cut.completed := by
        intro completed
        apply unfinished
        rw [nextCut]
        exact (prior.cut.completed_subset_complete event ready) completed
      have agreePrior : ∀ field, graph.FieldAvailable prior.cut field →
          graph.fieldPublic field → later field = prior.store field := by
        intro field available isPublic
        have availableNext : graph.FieldAvailable next.cut field := by
          cases field with
          | inl input => trivial
          | inr producer =>
              change producer ∈ next.cut.completed
              rw [nextCut]
              exact (prior.cut.completed_subset_complete event ready) available
        exact (agree field availableNext isPublic).trans
          (store_eq_of_step_of_available prior event ready action next member field available)
      rw [nextHistory, List.map_append, List.length_append]
      simp only [List.map_cons, List.map_nil, List.length_cons, List.length_nil]
      rw [show (prior.history.map Completion.event).length + 1 + fuel =
        (prior.history.map Completion.event).length + (fuel + 1) by omega]
      rw [ih agreePrior targetPrior (fuel + 1)]
      have observationEq :
          ({ completionOrder := prior.history.map Completion.event
             store := graph.replayPublicStore prior.cut later } : graph.PublicObservation) =
            graph.publicObserve prior := by
        apply PublicObservation.ext graph
        · rfl
        · exact replayPublicStore_eq_publicStore prior later agreePrior
      have selectedSubtype :
          scheduler
              { completionOrder := prior.history.map Completion.event
                store := graph.replayPublicStore prior.cut later }
              prior.cut.enabled
              (enabled_nonempty_of_not_terminal prior notTerminal) =
            ⟨event, (EventOrder.Cut.mem_enabled prior.cut event).mpr ready⟩ := by
        rw [observationEq]
        apply Subtype.ext
        exact selected
      rw [replayPrefixAux]
      simp [notTerminal, selectedSubtype, targetNe, nextCut]

/-- At the event selected by a scheduler-generated run, replay from the later
player-visible store reconstructs the actual chronological prefix exactly. -/
theorem SchedulerReachable.replayPrefix_eq_history
    {scheduler : graph.DeterministicPublicScheduler} {inputs : graph.Inputs}
    {config : graph.Config} (reachable : graph.SchedulerReachable scheduler inputs config)
    (notTerminal : ¬ config.cut.Terminal) (target : graph.EventId)
    (selected : (scheduler (graph.publicObserve config) config.cut.enabled
      (enabled_nonempty_of_not_terminal config notTerminal)).1 = target)
    (who : Player) :
    graph.replayPrefix scheduler target (graph.playerObserve who config).store =
      config.history.map Completion.event := by
  let selectedEvent := scheduler (graph.publicObserve config) config.cut.enabled
    (enabled_nonempty_of_not_terminal config notTerminal)
  have ready : config.cut.Ready target := by
    rw [← selected]
    exact (EventOrder.Cut.mem_enabled _ _).mp selectedEvent.2
  have unfinished : target ∉ config.cut.completed := ready.1
  have agree : ∀ field, graph.FieldAvailable config.cut field →
      graph.fieldPublic field →
      (graph.playerObserve who config).store field = config.store field := by
    intro field _ isPublic
    apply graph.playerStore_of_visible
    cases kind : graph.layout field <;>
      simp_all [fieldPublic, fieldVisibleTo, EventField.IsPublic, EventField.VisibleTo]
  have lengthLe : (config.history.map Completion.event).length ≤
      graph.order.eventCount := by
    have cardLe := config.history_nodup.length_le_card
    simpa using cardLe
  let fuel := graph.order.eventCount + 1 -
    (config.history.map Completion.event).length
  have fuelPositive : 0 < fuel := by
    dsimp [fuel]
    omega
  have totalFuel : (config.history.map Completion.event).length + fuel =
      graph.order.eventCount + 1 := by
    dsimp [fuel]
    omega
  have suffix := reachable.replayPrefixAux_suffix
    (graph.playerObserve who config).store agree target unfinished fuel
  rw [totalFuel] at suffix
  have observationEq :
      ({ completionOrder := config.history.map Completion.event
         store := graph.replayPublicStore config.cut
           (graph.playerObserve who config).store } : graph.PublicObservation) =
        graph.publicObserve config := by
    apply PublicObservation.ext graph
    · rfl
    · exact replayPublicStore_eq_publicStore config _ agree
  have selectedSubtype :
      scheduler
          { completionOrder := config.history.map Completion.event
            store := graph.replayPublicStore config.cut
              (graph.playerObserve who config).store }
          config.cut.enabled (enabled_nonempty_of_not_terminal config notTerminal) =
        ⟨target, (EventOrder.Cut.mem_enabled config.cut target).mpr ready⟩ := by
    rw [observationEq]
    apply Subtype.ext
    exact selected
  obtain ⟨rest, fuelEq⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt fuelPositive)
  rw [fuelEq] at suffix
  have replaySome : graph.replayPrefix? scheduler target
      (graph.playerObserve who config).store =
        some (config.history.map Completion.event) := by
    unfold replayPrefix?
    rw [suffix]
    rw [replayPrefixAux]
    simp [notTerminal, selectedSubtype]
  simp [replayPrefix, replaySome]

end Vegas.EventGraph
