/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import GameTheory.Analysis.Protocol.Sequential

/-! # Decisions inside actual continuation games

A decision reduction identifies a terminal decision problem at an information
site of an existing protocol. The latent state can vary across compatible
histories: the player optimizes its posterior reward, rather than being assumed
to know the state. The reduction must account for every whole-policy deviation
and provide legal policies realizing each pure decision.

The resulting support criterion uses the fixed utility of the game. It needs
neither a pair of conflicting utilities nor a utility-independent compiler.
It is local: consistency, the posterior itself, and any connection to an
initialized outcome law remain obligations of the enclosing game.
-/

noncomputable section

namespace GameTheory.Protocol.InformationModel

open GameTheory.Math.Probability

variable {ι : Type} [Fintype ι] [DecidableEq ι]
  {E : ExecutionProtocol ι} {M : InformationModel E}

/-- A whole continuation factors through a state-dependent terminal reward.
The response law is common to the histories in this information set, but the
reward need not be. Every pure action has a legal whole-policy implementation;
randomized alternatives already arise from arbitrary behavioral policies. -/
structure ContinuationDecision (M : InformationModel E)
    (utility : ι → E.History → ℝ) (fuel : Nat) (State Action : Type*) where
  player : ι
  site : M.InformationSite player
  state : M.InformationHistory player site.1 → State
  response : Profile M.behavioralSignature → FinDist Action
  reward : State → Action → ℝ
  policy : Action → M.BehavioralPolicy player
  history_value : ∀ profile (history : M.InformationHistory player site.1),
    (M.runBehavioralFrom profile fuel history.1).expect (utility player) =
      (response profile).expect (reward (state history))
  realize : ∀ profile action,
    response (Profile.update (sig := M.behavioralSignature) profile player (policy action)) =
      FinDist.pure action

namespace ContinuationDecision

variable {utility : ι → E.History → ℝ} {fuel : Nat} {State Action : Type*}
  (decision : M.ContinuationDecision utility fuel State Action)

/-- The assessment's actual conditional law, with no assumption that it is
degenerate, on path, or generated by a particular perturbation sequence. -/
def posterior (assessment : M.BehavioralAssessment) : FinDist State :=
  (assessment.belief decision.player decision.site).map decision.state

def expectedReward (assessment : M.BehavioralAssessment) (action : Action) : ℝ :=
  (decision.posterior assessment).expect fun state => decision.reward state action

/-- Whole-policy continuation values equal posterior decision rewards. -/
theorem continuation_value (assessment : M.BehavioralAssessment)
    (alternative : M.BehavioralPolicy decision.player) :
    (assessment.continuationContext decision.site (utility decision.player) fuel).value
        alternative =
      (decision.response (Profile.update (sig := M.behavioralSignature)
        assessment.strategy decision.player alternative)).expect
          (decision.expectedReward assessment) := by
  rw [BehavioralAssessment.continuationContext_value, FinDist.expect_bind]
  calc
    _ = (assessment.belief decision.player decision.site).expect (fun history =>
          (decision.response (Profile.update (sig := M.behavioralSignature)
            assessment.strategy decision.player alternative)).expect
              (decision.reward (decision.state history))) := by
      apply FinDist.expect_congr
      intro history _
      exact decision.history_value _ history
    _ = _ := by
      rw [FinDist.expect_comm]
      apply FinDist.expect_congr
      intro action _
      exact (FinDist.expect_map decision.state (assessment.belief decision.player decision.site)
        (fun state => decision.reward state action)).symm

/-- Checking all pure decisions suffices even though protocol sequential
rationality quantifies over whole behavioral continuation policies. -/
theorem rationalAt_iff (assessment : M.BehavioralAssessment) :
    assessment.IsSequentiallyRationalAt decision.site
        (assessment.continuationContext decision.site (utility decision.player) fuel) ↔
      ∀ action, decision.expectedReward assessment action ≤
        (decision.response assessment.strategy).expect (decision.expectedReward assessment) := by
  constructor
  · intro rational action
    have bound := rational (decision.policy action) (Set.mem_univ _)
    change (assessment.continuationContext decision.site (utility decision.player) fuel).value
        (decision.policy action) ≤
      (assessment.continuationContext decision.site (utility decision.player) fuel).value
        (assessment.strategy decision.player) at bound
    simpa only [decision.continuation_value, decision.realize, FinDist.expect_pure,
      Profile.update_eq_self] using bound
  · intro optimal alternative _
    change (assessment.continuationContext decision.site (utility decision.player) fuel).value
        alternative ≤
      (assessment.continuationContext decision.site (utility decision.player) fuel).value
        (assessment.strategy decision.player)
    rw [decision.continuation_value, decision.continuation_value, Profile.update_eq_self]
    exact FinDist.expect_le_of_forall _ _ _ fun action _ => optimal action

/-- Exact fixed-payoff criterion: a rational response assigns positive mass
only to actions maximizing expected reward under this information-set belief.
No finiteness of the action carrier is needed because laws have finite support. -/
theorem rationalAt_iff_support_maximal (assessment : M.BehavioralAssessment) :
    assessment.IsSequentiallyRationalAt decision.site
        (assessment.continuationContext decision.site (utility decision.player) fuel) ↔
      ∀ action ∈ (decision.response assessment.strategy).support, ∀ alternative,
        decision.expectedReward assessment alternative ≤
          decision.expectedReward assessment action := by
  rw [decision.rationalAt_iff]
  constructor
  · intro optimal action supported alternative
    have attained := FinDist.eq_of_expect_eq_of_le
      (decision.response assessment.strategy) (decision.expectedReward assessment)
      ((decision.response assessment.strategy).expect (decision.expectedReward assessment))
      (fun candidate _ => optimal candidate) rfl supported
    rw [attained]
    exact optimal alternative
  · intro maximal alternative
    have bound := FinDist.expect_mono
      (μ := decision.response assessment.strategy)
      (fun action supported => maximal action supported alternative)
    simpa only [FinDist.expect_const] using bound

theorem rational_support_maximal (assessment : M.BehavioralAssessment)
    (rational : assessment.IsSequentiallyRationalWithin utility fuel)
    (action : Action) (supported : action ∈ (decision.response assessment.strategy).support)
    (alternative : Action) :
    decision.expectedReward assessment alternative ≤ decision.expectedReward assessment action :=
  (decision.rationalAt_iff_support_maximal assessment).mp
    (rational decision.player decision.site) action supported alternative

/-- One strictly inferior supported response already excludes sequential
rationality for this single fixed utility. -/
theorem not_rational_of_supported_inferior (assessment : M.BehavioralAssessment)
    (action alternative : Action)
    (supported : action ∈ (decision.response assessment.strategy).support)
    (better : decision.expectedReward assessment action <
      decision.expectedReward assessment alternative) :
    ¬ assessment.IsSequentiallyRationalWithin utility fuel := by
  intro rational
  exact (not_le_of_gt better)
    (decision.rational_support_maximal assessment rational action supported alternative)

/-- A feasible pure decision provides a payoff lower bound for every
sequentially rational assessment, including assessments off the equilibrium path. -/
theorem rational_value_bound (assessment : M.BehavioralAssessment)
    (rational : assessment.IsSequentiallyRationalWithin utility fuel) (action : Action) :
    decision.expectedReward assessment action ≤
      (decision.response assessment.strategy).expect (decision.expectedReward assessment) :=
  (decision.rationalAt_iff assessment).mp (rational decision.player decision.site) action

/-- With a finite nonempty menu, the local value is exactly a pure maximum. -/
theorem rational_value_eq_maximum [Finite Action] [Nonempty Action]
    (assessment : M.BehavioralAssessment)
    (rational : assessment.IsSequentiallyRationalWithin utility fuel) :
    ∃ best,
      (∀ action, decision.expectedReward assessment action ≤
        decision.expectedReward assessment best) ∧
      (decision.response assessment.strategy).expect (decision.expectedReward assessment) =
        decision.expectedReward assessment best := by
  obtain ⟨best, maximal⟩ := Finite.exists_max (decision.expectedReward assessment)
  exact ⟨best, maximal, le_antisymm
    (FinDist.expect_le_of_forall _ _ _ fun action _ => maximal action)
    (decision.rational_value_bound assessment rational best)⟩

/-- Once retained alternatives have been checked, extending a local menu
requires exactly the no-gain inequalities for the omitted alternatives.
Their probability under the proposed strategy is irrelevant to this check.
This is a rationality criterion at an existing information site; it does not
construct the beliefs or additional sites of an extended game. -/
theorem rationalAt_iff_omitted_not_profitable (assessment : M.BehavioralAssessment)
    (retained : Set Action)
    (optimal : ∀ action ∈ retained, decision.expectedReward assessment action ≤
      (decision.response assessment.strategy).expect (decision.expectedReward assessment)) :
    assessment.IsSequentiallyRationalAt decision.site
        (assessment.continuationContext decision.site (utility decision.player) fuel) ↔
      ∀ action ∉ retained, decision.expectedReward assessment action ≤
        (decision.response assessment.strategy).expect (decision.expectedReward assessment) := by
  rw [decision.rationalAt_iff]
  constructor
  · exact fun rational action _ => rational action
  · intro omitted action
    by_cases kept : action ∈ retained
    · exact optimal action kept
    · exact omitted action kept

/-- A sufficient local omission certificate: each removed action is weakly
dominated by a retained action at every compatible history. The dominating
action must work throughout the information set, so no extra information is
silently supplied to the player. This covers every belief at the fixed site.
Global consistency and newly introduced information sites are separate. -/
theorem rationalAt_of_omitted_dominated (assessment : M.BehavioralAssessment)
    (retained : Set Action)
    (optimal : ∀ action ∈ retained, decision.expectedReward assessment action ≤
      (decision.response assessment.strategy).expect (decision.expectedReward assessment))
    (dominated : ∀ action ∉ retained, ∃ replacement ∈ retained, ∀ history,
      decision.reward (decision.state history) action ≤
        decision.reward (decision.state history) replacement) :
    assessment.IsSequentiallyRationalAt decision.site
      (assessment.continuationContext decision.site (utility decision.player) fuel) := by
  apply (decision.rationalAt_iff_omitted_not_profitable assessment retained optimal).mpr
  intro action omitted
  obtain ⟨replacement, kept, dominates⟩ := dominated action omitted
  apply le_trans _ (optimal replacement kept)
  simp only [expectedReward, posterior, FinDist.expect_map]
  exact FinDist.expect_mono fun history _ => dominates history

variable {OtherState : Type*}

/-- If an abstraction forces the same response at two decision sites, every
supported response must maximize both posterior rewards. This can obstruct
information erasure for one fixed utility, without changing the compiler's
utility parameter. The sites and assessments may have different beliefs. -/
theorem shared_response_requires_common_maximizer
    (other : M.ContinuationDecision utility fuel OtherState Action)
    (first second : M.BehavioralAssessment)
    (firstRational : first.IsSequentiallyRationalWithin utility fuel)
    (secondRational : second.IsSequentiallyRationalWithin utility fuel)
    (same : decision.response first.strategy = other.response second.strategy) :
    ∃ action,
      (∀ alternative, decision.expectedReward first alternative ≤
        decision.expectedReward first action) ∧
      (∀ alternative, other.expectedReward second alternative ≤
        other.expectedReward second action) := by
  obtain ⟨action, supported⟩ := (decision.response first.strategy).support_nonempty
  refine ⟨action, decision.rational_support_maximal first firstRational action supported, ?_⟩
  rw [same] at supported
  exact other.rational_support_maximal second secondRational action supported

end ContinuationDecision

end GameTheory.Protocol.InformationModel
