/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Interaction.MessageApplicationPolicies
import Interaction.SealedCandidateResolution

/-! # Erased rejected traffic and an unchanged adaptive wire

Two player policies submit different cleartext payloads, both rejected by the
candidate handler. Erasing that payload distinction identifies their complete
command prefixes. One fixed public wire nevertheless includes a pending honest
opening immediately in one case and delivers it before inclusion in the other.
Both runs include the opening within two wire invocations without advancing time.

This tests a common continuation kernel on the erased command trace: both
prefixes are generated by policies in the actual message runner, with the owner
and wire unchanged. The result concerns this particular trace projection, not
every logical local-history interface. It does not rule out outcome-only
strategic simulation, retained private recall of the erased payload, an
observation interface retaining rejected traffic, or another action translation.
-/

noncomputable section

namespace InteractionTests.LogicalCommitmentAdaptive

open Interaction Interaction.MessageApplication GameTheory.Math.Probability

private def runtime : SealedResolution Bool (Option Bool) :=
  ⟨⟨[⟨.commit false, []⟩, ⟨.reveal false 0, [0]⟩]⟩, none, 2⟩

private abbrev app := runtime.candidateApplication

private def initial : app.PolicyExecution :=
  PolicyExecution.initial app (State.initial app runtime.candidateInitial)

private def commitment : app.Payload := .commitment 0 (false, 0)

private def opening : app.Payload := .opening 1 (false, 0) (some true)

/-- The signal-bearing payload is rejected regardless of the application state. -/
theorem cleartext_tag_rejected (state : app.Application) (tag : Bool) :
    runtime.candidateHandle state ⟨(true, 0), .cleartext 7 (some tag)⟩ = none := by
  simp [SealedResolution.candidateHandle, SealedProgram.Payload.node?,
    SealedProgram.candidateMessage?]

/-- The owner is unchanged; the other principal controls only a rejected tag. -/
private def players (tag : Bool) : Bool → app.PlayerPolicy
  | false => fun history _ => FinDist.pure <| match history.length with
      | 0 => .privateCommand ⟨(0, some true)⟩
      | 1 => .submit commitment
      | _ => .submit opening
  | true => fun _ _ => FinDist.pure (.submit (.cleartext 7 (some tag)))

private def publicTag (view : app.EnvironmentObservation) : Bool :=
  view.pool.ledger.any fun message => match message.payload with
    | .cleartext _ (some true) => true
    | _ => false

/-- This wire reads public rejected traffic, never the private candidate table.
After a delivery it includes the opening on its next invocation. -/
private def wire : app.EnvironmentPolicy := fun history view => FinDist.pure <|
  match history.length with
  | 0 => .include (false, 0)
  | 1 => .include (true, 0)
  | _ => if publicTag view || !(view.pool.inbox true).isEmpty then
      .include (false, 1)
    else .deliver true (false, 1)

private def prefixSchedule : List (@Invocation Bool) :=
  [.player false, .player false, .environment, .player false, .player true, .environment]

/-- The claim quotient identifies cleartext garbage with malformed traffic.
Every other command, including private preparation and envelope references,
is retained. -/
private def eraseRejected : app.Action → app.Action
  | .submit who (.cleartext _ _) => .submit who .malformed
  | action => action

private def retainedPrefix (execution : app.PolicyExecution) : List app.Action :=
  execution.nativeTrace.map eraseRejected

private def logicalPrefix : List app.Action :=
  [.privateCommand false ⟨(0, some true)⟩,
    .submit false commitment, .include (false, 0), .submit false opening,
    .submit true .malformed, .include (true, 0)]

private def published (execution : app.PolicyExecution) : Option (Option Bool) :=
  execution.native.application.visible.published? 1

/-- Actual policies generate the same retained command history. -/
theorem erased_policy_prefix (tag : Bool) :
    (app.runPolicies (players tag) wire prefixSchedule initial).map retainedPrefix =
      FinDist.pure logicalPrefix := by
  simp only [prefixSchedule, MessageApplication.runPolicies, MessageApplication.invoke,
    players, wire, initial, MessageApplication.PolicyExecution.initial,
    MessageApplication.playerStep, MessageApplication.environmentPolicyStep,
    MessageApplication.advance, MessageApplication.PlayerCommand.toAction,
    MessageApplication.EnvironmentPolicyCommand.toAction, MessageApplication.step,
    FinDist.pure_bind, FinDist.map_pure, List.length_nil, List.length_cons,
    List.nil_append, List.cons_append, Nat.reduceAdd,
    Bool.true_eq_false, if_true, if_false]
  rfl

/-- The same wire gives different next publication laws after those prefixes. -/
theorem adaptive_next_publication (tag : Bool) :
    (app.runPolicies (players tag) wire (prefixSchedule ++ [.environment]) initial).map published =
      FinDist.pure (if tag then some (some true) else none) := by
  cases tag <;>
    simp only [prefixSchedule, List.cons_append, List.nil_append,
      MessageApplication.runPolicies, MessageApplication.invoke,
      players, wire, initial, MessageApplication.PolicyExecution.initial,
      MessageApplication.playerStep, MessageApplication.environmentPolicyStep,
      MessageApplication.advance, MessageApplication.PlayerCommand.toAction,
      MessageApplication.EnvironmentPolicyCommand.toAction, MessageApplication.step,
      FinDist.pure_bind, List.length_nil, List.length_cons, Nat.reduceAdd,
      Bool.true_eq_false, if_true, if_false] <;>
    dsimp [publicTag, app, SealedResolution.candidateApplication, SealedResolution.host,
      State.environmentView, State.initial, MessagePool.empty,
      MessageApplication.includePending, MessagePool.submit, MessagePool.deliver] <;>
    simp [MessagePool.includeApplication_pool, MessagePool.includePending,
      MessagePool.lookup, MessagePool.removeFirst, commitment,
      FinDist.pure_bind, FinDist.map_pure] <;> rfl

/-- The signal changes the next prefix, without preventing this honest opening:
both executions finish within two wire invocations and no clock action. -/
theorem adaptive_eventual_publication (tag : Bool) :
    (app.runPolicies (players tag) wire
      (prefixSchedule ++ [.environment, .environment]) initial).map published =
      FinDist.pure (some (some true)) := by
  cases tag <;>
    simp only [prefixSchedule, List.cons_append, List.nil_append,
      MessageApplication.runPolicies, MessageApplication.invoke,
      players, wire, initial, MessageApplication.PolicyExecution.initial,
      MessageApplication.playerStep, MessageApplication.environmentPolicyStep,
      MessageApplication.advance, MessageApplication.PlayerCommand.toAction,
      MessageApplication.EnvironmentPolicyCommand.toAction, MessageApplication.step,
      FinDist.pure_bind, List.length_nil, List.length_cons, Nat.reduceAdd,
      Bool.true_eq_false, if_true, if_false] <;>
    dsimp [publicTag, app, SealedResolution.candidateApplication, SealedResolution.host,
      State.environmentView, State.initial, MessagePool.empty,
      MessageApplication.includePending, MessagePool.submit, MessagePool.deliver] <;>
    simp [MessagePool.includeApplication_pool, MessagePool.includePending,
      MessagePool.lookup, MessagePool.removeFirst, commitment,
      FinDist.pure_bind, FinDist.map_pure] <;> rfl

/-- A single continuation on the erased history cannot reproduce both policy
laws under this unchanged wire, even when that continuation is randomized. -/
theorem no_common_erased_continuation :
    ¬ ∃ kernel : List app.Action → FinDist (Option (Option Bool)), ∀ tag,
      (app.runPolicies (players tag) wire
        (prefixSchedule ++ [.environment]) initial).map published =
        ((app.runPolicies (players tag) wire prefixSchedule initial).map
          retainedPrefix).bind kernel := by
  rintro ⟨kernel, hlaw⟩
  have hfalse := hlaw false
  have htrue := hlaw true
  rw [adaptive_next_publication, erased_policy_prefix, FinDist.pure_bind] at hfalse htrue
  have heq := hfalse.trans htrue.symm
  have hprob := congrArg (fun law : FinDist (Option (Option Bool)) => law.prob none) heq
  norm_num [FinDist.prob_pure_eq_ite] at hprob
  cases hprob

end InteractionTests.LogicalCommitmentAdaptive

/-- info: 'InteractionTests.LogicalCommitmentAdaptive.no_common_erased_continuation'
depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms InteractionTests.LogicalCommitmentAdaptive.no_common_erased_continuation
