/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.Game.RevealServiceRosterSupport
import GameTheoryExtensions.Math.Probability.Support

/-! # The common policy limit at every permitted roster prefix

The prefix is generated by arbitrary retained policies. Fully supported
source-choice and timing approximants converge to waiting until the final
owner visit, with an explicit stop rule after any earlier opening. Thus
zero-probability early openings use the same limit as on-path histories.
-/

noncomputable section

namespace Vegas

open SourceProgram

open GameTheory.Math.Probability Interaction EventGraphRuntime

private theorem hazard_tendsto_final {slots : Nat} (last : Fin slots)
    (final : last.val + 1 = slots) {probability : Nat → ℝ} {limit : ℝ}
    (probabilityConverges : Filter.Tendsto probability Filter.atTop (nhds limit))
    {timing : Nat → PMF (Fin slots)}
    (timingConverges : PMFConvergesPointwise timing (PMF.pure last))
    (slot : Fin slots) :
    Filter.Tendsto (fun n => PMF.deferredHazard (probability n) (timing n) slot.val)
      Filter.atTop (nhds (if slot = last then limit else 0)) := by
  have prefixLimit := PMF.timingPrefix_tendsto timingConverges slot.val
  have zero : (PMF.pure last).timingPrefix slot.val = 0 := by
    apply Finset.sum_eq_zero
    intro earlier _
    by_cases before : earlier.val < slot.val
    · have different : earlier ≠ last := by
        intro same
        subst earlier
        omega
      simp only [before, ↓reduceIte, toReal_pure_apply, different]
    · simp only [before, ↓reduceIte]
  rw [zero] at prefixLimit
  have one : Filter.Tendsto (fun _ : Nat => (1 : ℝ)) Filter.atTop (nhds 1) :=
    tendsto_const_nhds
  have denominator := one.sub (probabilityConverges.mul prefixLimit)
  have numerator := probabilityConverges.mul (timingConverges.toReal slot)
  have quotient := numerator.div denominator (by norm_num : (1 : ℝ) - limit * 0 ≠ 0)
  simpa only [PMF.deferredHazard_at, PMF.deferredSurvival,
    toReal_pure_apply, mul_ite, mul_zero, mul_one, sub_zero, div_one,
    Pi.div_def] using quotient

variable {Player : Type} [DecidableEq Player] [Fintype Player]
  {L : IExpr} [IExpr.ResultTypes L]
  (setup : Setup (Player := Player) (L := L))
  (leaks : MessageNetwork.ObservationRule Player (WitnessedPacket (graph setup)))
  (bounds : MessageBounds (graph setup))
  (rosters : (graph setup).EventId → List Player)

open Classical in
/-- One common perturbation converges at every actual retained owner prefix.
The initial configuration and prefix may themselves be off the limiting path;
they need only be legal under the retained menu. -/
theorem roster_owner_mixture_limit
    (initial : (application setup leaks).Execution)
    (event : (graph setup).EventId) (owner : Player)
    (sole : initial.application.publicView.SoleReady event)
    (ownedEvent : (graph setup).actor? event = some owner)
    (candidate : Handle (graph setup)) (raw : Raw L)
    (opening : rosterOpening? setup leaks owner event
      (initial.observe (application setup leaks) owner) = some (candidate, raw))
    (owned : candidate.1 = owner)
    (valid : initial.application.candidates.lookup candidate = .openable raw)
    (offset : (initial.recall owner).length = rosterOffset setup rosters owner event)
    (serials : initial.network.SerialsBeforeNext)
    (published : initial.network.Satisfies fun message =>
      message.id ∈ initial.network.ledger.map Message.id)
    (players : Player → (application setup leaks).Policy)
    (covered : ∀ who history view response, response ∈ (players who history view).support →
      response ∈ rosterActions setup leaks bounds rosters who history view)
    (network : (runtime setup).NetworkPolicy leaks) (visits : List Player)
    (inside : visits.count owner < (rosters event).count owner)
    (current : (application setup leaks).Execution)
    (reached : current ∈ ((runtime setup).runInteractionPlan leaks players network
      (visits.map ServiceInstruction.player) initial).support)
    (sample : Finset (MessageId Player))
    (choice : Nat → PMF Bool) (choiceFull : ∀ n, FullSupport (choice n))
    (limit : PMF Bool) (choiceConverges : PMFConvergesPointwise choice limit)
    (timing : Nat → PMF (Fin ((rosters event).count owner)))
    (timingFull : ∀ n, FullSupport (timing n))
    (last : Fin ((rosters event).count owner)) (final : last.val + 1 = (rosters event).count owner)
    (timingConverges : PMFConvergesPointwise timing (PMF.pure last)) :
    let app := application setup leaks
    let activated := current.sampledActivation app owner sample
    let past := activated.recall owner
    let view := activated.observe app owner
    let opening := (runtime setup).windowOpening leaks event candidate raw
    PMFConvergesPointwise (fun n =>
      ((app.policyMixture (rosterSelection (choice n) (timing n)) (fun selected =>
        app.scheduledPolicy (rosterOffset setup rosters owner event) selected
          (fun _ _ => PMF.pure opening) app.silentPolicy)).policy past view))
      (if ∃ entry ∈ past.drop (rosterOffset setup rosters owner event), entry.action = opening then
        app.silentPolicy past view
      else if past.length + 1 = rosterOffset setup rosters owner event +
          (rosters event).count owner then
        limit.bind (fun disclose => if disclose then PMF.pure opening
          else app.silentPolicy past view)
      else app.silentPolicy past view) := by
  classical
  dsimp only
  let app := application setup leaks
  let activated := current.sampledActivation app owner sample
  let past := activated.recall owner
  let view := activated.observe app owner
  let packet := (runtime setup).windowOpening leaks event candidate raw
  change PMFConvergesPointwise (fun n =>
    ((app.policyMixture (rosterSelection (choice n) (timing n)) (fun selected =>
      app.scheduledPolicy (rosterOffset setup rosters owner event) selected
        (fun _ _ => PMF.pure packet) app.silentPolicy)).policy past view))
    (if ∃ entry ∈ past.drop (rosterOffset setup rosters owner event), entry.action = packet then
      app.silentPolicy past view
    else if past.length + 1 = rosterOffset setup rosters owner event +
        (rosters event).count owner then
      limit.bind (fun disclose => if disclose then PMF.pure packet
        else app.silentPolicy past view)
    else app.silentPolicy past view)
  obtain ⟨selected, frame, earlier, recorded, posterior⟩ :=
    roster_window_posterior setup leaks bounds rosters initial event owner sole ownedEvent
      candidate raw opening owned valid offset serials published players covered network visits
        inside.le current reached
  have counts : past.length = rosterOffset setup rosters owner event + visits.count owner :=
    frame.count
  have full n := rosterSelection_fullSupport (choice n) (timing n) (choiceFull n) (timingFull n)
  have small n : ((choice n) true).toReal < 1 := by
    have positive := pmf_toReal_pos_iff.mpr (choiceFull n false)
    have total := pmf_sum_toReal_eq_one (choice n)
    simp only [Fintype.sum_bool] at total
    linarith
  cases selected with
  | some slot =>
      have seen : ∃ entry ∈ past.drop (rosterOffset setup rosters owner event),
          entry.action = packet := recorded.mp rfl
      rw [ite_eq_left seen]
      have stopped n :
          ((app.policyMixture (rosterSelection (choice n) (timing n)) (fun selected =>
            app.scheduledPolicy (rosterOffset setup rosters owner event) selected
              (fun _ _ => PMF.pure packet) app.silentPolicy)).policy past view) =
                app.silentPolicy past view := by
        have fixed : ((app.policyMixture (rosterSelection (choice n) (timing n))
            (fun selected => app.scheduledPolicy (rosterOffset setup rosters owner event) selected
              (fun _ _ => PMF.pure packet) app.silentPolicy)).posterior past) =
                PMF.pure (some slot) := posterior _ (full n)
        rw [app.policyMixture_policy, fixed, PMF.pure_bind]
        unfold ReactiveApplication.scheduledPolicy
        apply ite_eq_right
        simp only [Option.map_some]
        intro equal
        have same := Option.some.inj equal
        change rosterOffset setup rosters owner event + slot.val = past.length at same
        have before := earlier slot rfl
        omega
      intro action
      simp only [stopped]
      exact tendsto_const_nhds
  | none =>
      have unseen : ¬ ∃ entry ∈ past.drop (rosterOffset setup rosters owner event),
          entry.action = packet := fun present => Bool.noConfusion (recorded.mpr present)
      rw [ite_eq_right unseen]
      let slot : Fin ((rosters event).count owner) := ⟨visits.count owner, inside⟩
      have atSlot : past.length = rosterOffset setup rosters owner event + slot.val := counts
      have probabilities n action :
          ((((app.policyMixture (rosterSelection (choice n) (timing n)) (fun selected =>
            app.scheduledPolicy (rosterOffset setup rosters owner event) selected
              (fun _ _ => PMF.pure packet) app.silentPolicy)).policy past view)) action).toReal =
            PMF.deferredHazard (((choice n) true).toReal) (timing n) slot.val *
                ((PMF.pure packet) action).toReal +
              (1 - PMF.deferredHazard (((choice n) true).toReal) (timing n) slot.val) *
                ((app.silentPolicy past view) action).toReal := by
        have representation :=
          PMF.bind_bool_mix (choice n) ((timing n).map some) (PMF.pure none)
        change rosterSelection (choice n) (timing n) = _ at representation
        have exactPost := posterior _ (full n)
        simp only [representation] at exactPost ⊢
        exact app.scheduledMixture_probability_of_posterior (((choice n) true).toReal)
          (ENNReal.toReal_nonneg) (small n) (timing n)
          (rosterOffset setup rosters owner event) packet app.silentPolicy past slot atSlot
          exactPost view action
      have lastIff : slot = last ↔ past.length + 1 =
          rosterOffset setup rosters owner event + (rosters event).count owner := by
        constructor
        · intro same
          have := congrArg Fin.val same
          omega
        · intro same
          apply Fin.ext
          omega
      have hazard := hazard_tendsto_final last final (choiceConverges.toReal true) timingConverges
        slot
      rw [pmfConvergesPointwise_iff_toReal]
      intro action
      have one : Filter.Tendsto (fun _ : Nat => (1 : ℝ)) Filter.atTop (nhds 1) :=
        tendsto_const_nhds
      have combined := (hazard.mul_const (((PMF.pure packet) action).toReal)).add
        ((one.sub hazard).mul_const (((app.silentPolicy past view) action).toReal))
      have actual := combined.congr' (Filter.Eventually.of_forall
        (fun n => (probabilities n action).symm))
      by_cases finalSlot : slot = last
      · rw [ite_eq_left (lastIff.mp finalSlot), PMF.bind_bool_mix]
        simpa only [finalSlot, ↓reduceIte, mix_apply_toReal] using actual
      · rw [ite_eq_right (fun same => finalSlot (lastIff.mpr same))]
        simpa only [finalSlot, ↓reduceIte, zero_mul, sub_zero, one_mul, zero_add] using actual

omit [Fintype Player] in
open Classical in
theorem rosterLimitPolicy_at_phase
    (profile : BehavioralProfile setup.program)
    (initial current : (application setup leaks).Execution)
    (event : (graph setup).EventId) (owner : Player)
    (sole : initial.application.publicView.SoleReady event)
    (owned : (graph setup).actor? event = some owner)
    (candidate : Handle (graph setup)) (raw : Raw L)
    (opening : rosterOpening? setup leaks owner event
      (initial.observe (application setup leaks) owner) = some (candidate, raw))
    (unchanged : current.application = initial.application) :
    let app := application setup leaks
    let past := current.recall owner
    let view := current.observe app owner
    let packet := (runtime setup).windowOpening leaks event candidate raw
    rosterLimitPolicy setup leaks rosters profile owner past view =
      if ∃ entry ∈ past.drop (rosterOffset setup rosters owner event), entry.action = packet then
        app.silentPolicy past view
      else if past.length + 1 = rosterOffset setup rosters owner event +
          (rosters event).count owner then
        (sourceChoiceLaw setup leaks profile owner (initial.observe app owner)).bind
          (fun disclose => if disclose then PMF.pure packet else app.silentPolicy past view)
      else app.silentPolicy past view := by
  have turn :
      (current.observe (application setup leaks) owner).application.publicView.ownTurn? owner =
        some event := by
    change current.application.publicView.ownTurn? owner = some event
    rw [unchanged]
    exact PublicView.ownTurn?_of_ownTurn _ owner event (sole.ownTurn owned)
  dsimp only
  unfold rosterLimitPolicy
  rw [turn]
  dsimp only
  rw [ite_eq_left owned]
  rw [rosterOpening?_application_eq setup leaks owner event current initial unchanged, opening]
  dsimp only
  simp only [Bool.or_eq_true, List.any_eq_true, decide_eq_true_eq]
  rw [sourceChoiceLaw_application_eq setup leaks profile owner current initial unchanged]
  rw [ite_or, ite_not]

/-- The common limit is the single globally defined native compiler policy,
not a family selected separately at each history. The source choice law is
read from the owner's actual application observation. -/
theorem roster_owner_policy_limit
    (initial : (application setup leaks).Execution)
    (event : (graph setup).EventId) (owner : Player)
    (sole : initial.application.publicView.SoleReady event)
    (ownedEvent : (graph setup).actor? event = some owner)
    (candidate : Handle (graph setup)) (raw : Raw L)
    (opening : rosterOpening? setup leaks owner event
      (initial.observe (application setup leaks) owner) = some (candidate, raw))
    (owned : candidate.1 = owner)
    (valid : initial.application.candidates.lookup candidate = .openable raw)
    (offset : (initial.recall owner).length = rosterOffset setup rosters owner event)
    (serials : initial.network.SerialsBeforeNext)
    (published : initial.network.Satisfies fun message =>
      message.id ∈ initial.network.ledger.map Message.id)
    (players : Player → (application setup leaks).Policy)
    (covered : ∀ who history view response, response ∈ (players who history view).support →
      response ∈ rosterActions setup leaks bounds rosters who history view)
    (network : (runtime setup).NetworkPolicy leaks) (visits : List Player)
    (inside : visits.count owner < (rosters event).count owner)
    (current : (application setup leaks).Execution)
    (reached : current ∈ ((runtime setup).runInteractionPlan leaks players network
      (visits.map ServiceInstruction.player) initial).support)
    (sample : Finset (MessageId Player))
    (profiles : Nat → BehavioralProfile setup.program) (source : BehavioralProfile setup.program)
    (choiceFull : ∀ n, FullSupport (sourceChoiceLaw setup leaks (profiles n) owner
      (initial.observe (application setup leaks) owner)))
    (choiceConverges : PMFConvergesPointwise
      (fun n => sourceChoiceLaw setup leaks (profiles n) owner
        (initial.observe (application setup leaks) owner))
      (sourceChoiceLaw setup leaks source owner (initial.observe (application setup leaks) owner)))
    (timing : Nat → TimingLaw setup rosters)
    (timingFull : ∀ n, FullSupport (timing n event owner ownedEvent))
    (last : Fin ((rosters event).count owner)) (final : last.val + 1 = (rosters event).count owner)
    (timingConverges : PMFConvergesPointwise
      (fun n => timing n event owner ownedEvent) (PMF.pure last)) :
    let activated := current.sampledActivation (application setup leaks) owner sample
    PMFConvergesPointwise
      (fun n => rosterPolicy setup leaks rosters (timing n) (profiles n) owner
        (activated.recall owner) (activated.observe (application setup leaks) owner))
      (rosterLimitPolicy setup leaks rosters source owner
        (activated.recall owner) (activated.observe (application setup leaks) owner)) := by
  let app := application setup leaks
  let activated := current.sampledActivation app owner sample
  obtain ⟨selected, frame, _⟩ := roster_window_support setup leaks bounds rosters
    initial event owner sole ownedEvent candidate raw opening owned valid offset serials
      published players covered network visits inside.le current reached
  have unchanged : activated.application = initial.application := frame.application
  have actual := roster_owner_mixture_limit setup leaks bounds rosters initial event owner
    sole ownedEvent candidate raw opening owned valid offset serials published players covered
      network visits inside current reached sample
      (fun n => sourceChoiceLaw setup leaks (profiles n) owner (initial.observe app owner))
      choiceFull (sourceChoiceLaw setup leaks source owner (initial.observe app owner))
      choiceConverges (fun n => timing n event owner ownedEvent) timingFull last final
        timingConverges
  dsimp only at actual ⊢
  rw [rosterLimitPolicy_at_phase setup leaks rosters source initial activated event owner
    sole ownedEvent candidate raw opening unchanged]
  convert actual using 1
  ext n action
  have same := rosterPolicy_at_phase setup leaks rosters (timing n) (profiles n)
    initial activated event owner sole ownedEvent candidate raw opening unchanged owner
  simpa only [EventGraphRuntime.openingWindowMixturePlayers, Function.update_self] using
    congrArg (fun (law : PMF app.Action) => law action) same

end Vegas
