/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.Game.RevealServiceRosterSupport
import Vegas.Pending.ReactiveOpeningContinuation

/-! # The remaining disclosure law at every retained phase prefix

The phase prefix may have been generated by arbitrary retained responses.
Its actual owner recall either records an earlier opening or conditions the
original timing law on still-available slots. The global compiled policy then
settles with exactly that conditional source-choice law.
-/

noncomputable section

namespace Vegas

open SourceProgram

open GameTheory.Math.Probability Interaction EventGraphRuntime

variable {Player : Type} [DecidableEq Player] [Fintype Player]
  {L : IExpr} [IExpr.ResultTypes L]

omit [Fintype Player] in
private theorem inclusion_players
    (setup : Setup (Player := Player) (L := L))
    (leaks : MessageNetwork.ObservationRule Player (WitnessedPacket (graph setup)))
    (left right : Player → (application setup leaks).Policy)
    (network : (runtime setup).NetworkPolicy leaks) (event : (graph setup).EventId) (owner : Player)
    (current : (application setup leaks).Execution) :
    (runtime setup).runInteractionPlan leaks left network [.includeLatest event owner] current =
      (runtime setup).runInteractionPlan leaks right network [.includeLatest event owner] current :=
    by
  simp only [runInteractionPlan, PMF.bind_pure, interactionStep, interactionInstruction,
    PMF.pure_bind]
  unfold reactiveLatest
  split <;> rfl

theorem roster_remaining_settlement
    (setup : Setup (Player := Player) (L := L))
    (leaks : MessageNetwork.ObservationRule Player (WitnessedPacket (graph setup)))
    (bounds : MessageBounds (graph setup)) (rosters : (graph setup).EventId → List Player)
    (timing : TimingLaw setup rosters)
    (profile : BehavioralProfile setup.program)
    (initial : (application setup leaks).Execution)
    (event : (graph setup).EventId) (owner : Player)
    (sole : initial.application.publicView.SoleReady event)
    (ownedEvent : (graph setup).actor? event = some owner)
    (candidate : Handle (graph setup)) (raw : Raw L)
    (opening : rosterOpening? setup leaks owner event
      (initial.observe (application setup leaks) owner) = some (candidate, raw))
    (owned : candidate.1 = owner)
    (valid : initial.application.candidates.lookup candidate = .openable raw)
    (offset : (initial.recall owner).length = rosterOffset setup rosters owner event)
    (serials : initial.network.SerialsBeforeNext)
    (published : initial.network.Satisfies fun message =>
      message.id ∈ initial.network.ledger.map Message.id)
    (players : Player → (application setup leaks).Policy)
    (covered : ∀ who history view response, response ∈ (players who history view).support →
      response ∈ rosterActions setup leaks bounds rosters who history view)
    (network : (runtime setup).NetworkPolicy leaks) (visited remaining : List Player)
    (complete : visited.count owner + remaining.count owner = (rosters event).count owner)
    (current : (application setup leaks).Execution)
    (reached : current ∈ ((runtime setup).runInteractionPlan leaks players network
      (visited.map ServiceInstruction.player) initial).support)
    (choiceFull : FullSupport (sourceChoiceLaw setup leaks profile owner
      (initial.observe (application setup leaks) owner)))
    (timingFull : FullSupport (timing event owner ownedEvent)) :
    let app := application setup leaks
    let choices := rosterSelection (sourceChoiceLaw setup leaks profile owner
      (initial.observe app owner)) (timing event owner ownedEvent)
    ∃ selected : Option (Fin ((rosters event).count owner)),
      (selected.isSome ↔ ∃ entry ∈
        (current.recall owner).drop (rosterOffset setup rosters owner event),
          entry.action = (runtime setup).windowOpening leaks event candidate raw) ∧
      ((runtime setup).runInteractionPlan leaks
        (rosterPolicy setup leaks rosters timing profile) network
        (remaining.map ServiceInstruction.player ++ [.includeLatest event owner]) current).map
          (fun final => final.application) =
        (match selected with
          | none => choices.filter (ReactiveApplication.remainingOpeningSlots (visited.count owner))
              ⟨none, True.intro, rosterSelection_fullSupport _ _ choiceFull timingFull none⟩
          | some slot => PMF.pure (some slot)).map
          (fun mode : Option (Fin ((rosters event).count owner)) => if mode.isSome then
            (app.handle initial.application
              ((runtime setup).windowEnvelope leaks owner event candidate raw initial)).getD
                initial.application else initial.application) := by
  intro app choices
  have full : FullSupport choices := rosterSelection_fullSupport _ _ choiceFull timingFull
  obtain ⟨selected, frame, _past, recorded, exactModes⟩ :=
    roster_window_posterior setup leaks bounds rosters initial event owner sole ownedEvent
      candidate raw opening owned valid offset serials
      published players covered network visited (by omega) current reached
  let family := fun mode : Option (Fin ((rosters event).count owner)) =>
    app.scheduledPolicy (rosterOffset setup rosters owner event) mode
      (fun _ _ => PMF.pure ((runtime setup).windowOpening leaks event candidate raw))
        app.silentPolicy
  let posterior := (app.policyMixture choices family).posterior (current.recall owner)
  have frames (mode : Option (Fin ((rosters event).count owner)))
      (possible : mode ∈ posterior.support) :
      (runtime setup).OpeningWindowFrame leaks owner event candidate raw
        (rosterOffset setup rosters owner event) mode (visited.count owner) initial current := by
    change mode ∈ ((app.policyMixture choices family).posterior (current.recall owner)).support
      at possible
    have modes := exactModes choices full
    cases selected with
    | none =>
        rw [modes] at possible
        have kept := ((PMF.mem_support_filter_iff _).mp possible).1
        apply frame.relabel (runtime setup) leaks owner event candidate raw
          (rosterOffset setup rosters owner event) none mode (visited.count owner) initial current
        cases mode with
        | none => rfl
        | some slot =>
            change visited.count owner ≤ slot.val at kept
            simp only [openingPassed, Option.any_some, Option.any_none,
              decide_eq_false_iff_not, not_lt]
            exact kept
    | some slot =>
        rw [modes, PMF.mem_support_pure_iff _ _] at possible
        cases possible
        exact frame
  have law := (runtime setup).openingWindowMixture_continuation_settlement leaks owner event
    candidate raw (rosterOffset setup rosters owner event) choices (visited.count owner)
      initial current serials owned valid remaining complete network frames
  have same : (runtime setup).runInteractionPlan leaks
      (rosterPolicy setup leaks rosters timing profile) network
        (remaining.map ServiceInstruction.player ++ [.includeLatest event owner]) current =
      (runtime setup).runInteractionPlan leaks
        ((runtime setup).openingWindowMixturePlayers leaks owner event candidate raw
          (rosterOffset setup rosters owner event) choices) network
        (remaining.map ServiceInstruction.player ++ [.includeLatest event owner]) current := by
    rw [runInteractionPlan_append, runInteractionPlan_append,
      rosterPolicy_window_eq setup leaks rosters timing profile initial current event owner
        sole ownedEvent candidate raw opening frame.application network remaining]
    apply bind_congr_on_support _
    intro next _
    exact inclusion_players setup leaks _ _ network event owner next
  refine ⟨selected, recorded, ?_⟩
  rw [same, law, exactModes choices full]
  rfl

end Vegas
