/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.Game.RevealServiceRosterWindowContinuation
import GameTheoryExtensions.Math.Probability.Support

/-! # Conditional disclosure values inside an actual revelation phase

The conditional mode law is obtained from actual private response recall.
Waiting changes the remaining binary probability by at most passed timing
mass. The bound is uniform over the source disclosure probability.
-/

noncomputable section

namespace Vegas

open SourceProgram

open GameTheory.Math.Probability Interaction EventGraphRuntime

theorem rosterSelection_waiting_value {slots : Nat} (choice : PMF Bool)
    (full : FullSupport choice) (timing : PMF (Fin slots)) (count : Nat)
    (whenTrue whenFalse : ℝ) :
    expect ((rosterSelection choice timing).filter
      (ReactiveApplication.remainingOpeningSlots count)
      ⟨none, True.intro, by
        rw [rosterSelection, PMF.support_bind]
        exact Set.mem_iUnion₂.mpr ⟨false, full false, by simp⟩⟩)
          (fun selected => if selected.isSome then whenTrue else whenFalse) =
      PMF.deferredRemaining ((choice true).toReal) timing count * whenTrue +
        (1 - PMF.deferredRemaining ((choice true).toReal) timing count) * whenFalse := by
  have total := pmf_sum_toReal_eq_one choice
  simp only [Fintype.sum_bool] at total
  have small : (choice true).toReal < 1 := by
    have positive := pmf_toReal_pos_iff.mpr (full false)
    linarith
  have representation := PMF.bind_bool_mix choice (timing.map some) (PMF.pure none)
  change rosterSelection choice timing = _ at representation
  simpa only [representation] using
    ReactiveApplication.remainingOpeningSlots_value ((choice true).toReal)
      (ENNReal.toReal_nonneg) small timing count whenTrue whenFalse

variable {Player : Type} [DecidableEq Player] [Fintype Player]
  {L : IExpr} [IExpr.ResultTypes L]

/-- At any actual retained prefix before the first own opening, the global
compiled policy's remaining inclusion value has the exact conditional binary
form. The prefix may have been generated by arbitrary retained policies. -/
theorem roster_waiting_settlement_value
    (setup : Setup (Player := Player) (L := L))
    (leaks : MessageNetwork.ObservationRule Player (WitnessedPacket (graph setup)))
    (bounds : MessageBounds (graph setup)) (rosters : (graph setup).EventId → List Player)
    (timing : TimingLaw setup rosters)
    (profile : BehavioralProfile setup.program)
    (initial : (application setup leaks).Execution)
    (event : (graph setup).EventId) (owner : Player)
    (granted : initial.application.serviceGrant = some event)
    (ownedEvent : (graph setup).actor? event = some owner)
    (candidate : Handle (graph setup)) (raw : Raw L)
    (opening : rosterOpening? setup leaks owner event
      (initial.observe (application setup leaks) owner) = some (candidate, raw))
    (owned : candidate.1 = owner)
    (valid : initial.application.candidates.lookup candidate = .openable raw)
    (offset : (initial.recall owner).length = rosterOffset setup rosters owner event)
    (serials : initial.network.SerialsBeforeNext)
    (published : initial.network.Satisfies fun message =>
      message.id ∈ initial.network.ledger.map Message.id)
    (players : Player → (application setup leaks).Policy)
    (covered : ∀ who history view response, response ∈ (players who history view).support →
      response ∈ rosterActions setup leaks bounds rosters who history view)
    (network : (runtime setup).NetworkPolicy leaks) (visited remaining : List Player)
    (complete : visited.count owner + remaining.count owner = (rosters event).count owner)
    (current : (application setup leaks).Execution)
    (reached : current ∈ ((runtime setup).runInteractionPlan leaks players network
      (visited.map ServiceInstruction.player) initial).support)
    (choiceFull : FullSupport (sourceChoiceLaw setup leaks profile owner
      (initial.observe (application setup leaks) owner)))
    (timingFull : FullSupport (timing event owner ownedEvent))
    (unopened : ¬ ∃ entry ∈
      (current.recall owner).drop (rosterOffset setup rosters owner event),
        entry.action = (runtime setup).windowOpening leaks event candidate raw)
    (value : EventGraphRuntime.State (graph := graph setup) → ℝ) :
    let app := application setup leaks
    let probability := ((sourceChoiceLaw setup leaks profile owner
      (initial.observe app owner)) true).toReal
    let success := (app.handle initial.application
      ((runtime setup).windowEnvelope leaks owner event candidate raw initial)).getD
        initial.application
    expect ((runtime setup).runInteractionPlan leaks
      (rosterPolicy setup leaks rosters timing profile) network
      (remaining.map ServiceInstruction.player ++ [.includeLatest event owner]) current)
        (fun final => value final.application) =
      PMF.deferredRemaining probability (timing event owner ownedEvent)
        (visited.count owner) * value success +
      (1 - PMF.deferredRemaining probability (timing event owner ownedEvent)
        (visited.count owner)) * value initial.application := by
  intro app probability success
  obtain ⟨selected, recorded, law⟩ := roster_remaining_settlement setup leaks bounds rosters
    timing profile initial event owner granted ownedEvent candidate raw opening owned valid
    offset serials published players covered network visited remaining complete current reached
    choiceFull timingFull
  have absent : selected = none := by
    cases selected with
    | none => rfl
    | some slot => exact False.elim (unopened (recorded.mp rfl))
  subst selected
  simp only at law
  have values := congrArg (fun distribution => expect distribution value) law
  simp only [expect_map] at values
  rw [values]
  have conditional := rosterSelection_waiting_value
    (sourceChoiceLaw setup leaks profile owner (initial.observe app owner)) choiceFull
      (timing event owner ownedEvent) (visited.count owner) (value success)
        (value initial.application)
  convert conditional using 1
  apply expect_congr_on_support
  intro mode _
  cases mode <;> rfl

open Classical in
/-- A local response before the first opening either fixes the source true
branch or leaves the exact remaining posterior for later opportunities.
Every legal silence/replay alias has the latter value. -/
theorem roster_owner_response_value
    (setup : Setup (Player := Player) (L := L))
    (leaks : MessageNetwork.ObservationRule Player (WitnessedPacket (graph setup)))
    (bounds : MessageBounds (graph setup)) (rosters : (graph setup).EventId → List Player)
    (initial : (application setup leaks).Execution)
    (event : (graph setup).EventId) (owner : Player)
    (granted : initial.application.serviceGrant = some event)
    (ownedEvent : (graph setup).actor? event = some owner)
    (candidate : Handle (graph setup)) (raw : Raw L)
    (opening : rosterOpening? setup leaks owner event
      (initial.observe (application setup leaks) owner) = some (candidate, raw))
    (owned : candidate.1 = owner)
    (valid : initial.application.candidates.lookup candidate = .openable raw)
    (offset : (initial.recall owner).length = rosterOffset setup rosters owner event)
    (serials : initial.network.SerialsBeforeNext)
    (published : initial.network.Satisfies fun message =>
      message.id ∈ initial.network.ledger.map Message.id)
    (players : Player → (application setup leaks).Policy)
    (covered : ∀ who history view response, response ∈ (players who history view).support →
      response ∈ rosterActions setup leaks bounds rosters who history view)
    (network : (runtime setup).NetworkPolicy leaks) (visited : List Player)
    (inside : visited.count owner < (rosters event).count owner)
    (current : (application setup leaks).Execution)
    (reached : current ∈ ((runtime setup).runInteractionPlan leaks players network
      (visited.map ServiceInstruction.player) initial).support)
    (sample : Finset (MessageId Player)) (action : (application setup leaks).Action)
    (member : action ∈ rosterActions setup leaks bounds rosters owner
      ((current.sampledActivation (application setup leaks) owner sample).recall owner)
      ((current.sampledActivation (application setup leaks) owner sample).observe
        (application setup leaks) owner))
    (unopened : ¬ ∃ entry ∈
      (current.recall owner).drop (rosterOffset setup rosters owner event),
        entry.action = (runtime setup).windowOpening leaks event candidate raw)
    (choice : PMF Bool) (choiceFull : FullSupport choice)
    (timing : PMF (Fin ((rosters event).count owner))) (timingFull : FullSupport timing)
    (whenTrue whenFalse : ℝ) :
    let app := application setup leaks
    let packet := (runtime setup).windowOpening leaks event candidate raw
    let policies := fun mode => app.scheduledPolicy (rosterOffset setup rosters owner event) mode
      (fun _ _ => PMF.pure packet) app.replayPolicy
    let after := (current.sampledActivation app owner sample).respond app owner action
    expect ((app.policyMixture (rosterSelection choice timing) policies).posterior
      (after.recall owner))
        (fun selected => if selected.isSome then whenTrue else whenFalse) =
      if action = packet then whenTrue else
        PMF.deferredRemaining ((choice true).toReal) timing (visited.count owner + 1) * whenTrue +
          (1 - PMF.deferredRemaining ((choice true).toReal) timing (visited.count owner + 1)) *
            whenFalse := by
  classical
  intro app packet policies after
  obtain ⟨selected, _frame, _recorded, same, posterior⟩ :=
    roster_response_posterior setup leaks bounds rosters initial event owner granted ownedEvent
      candidate raw opening owned valid offset serials published players covered network visited
      current reached owner sample action member (by simp only [↓reduceIte]; omega)
  have selectedIff : selected.isSome ↔ action = packet := by
    simpa only [unopened, false_or, true_and] using same
  have exactModes := posterior (rosterSelection choice timing)
    (rosterSelection_fullSupport choice timing choiceFull timingFull)
  rw [exactModes]
  cases selected with
  | none =>
      have unequal : action ≠ packet := fun equal => by simpa using selectedIff.mpr equal
      rw [ite_eq_right unequal]
      simpa only [↓reduceIte] using rosterSelection_waiting_value choice choiceFull timing
        (visited.count owner + 1) whenTrue whenFalse
  | some slot =>
      rw [ite_eq_left (selectedIff.mp rfl), expect_pure]
      rfl

end Vegas
