/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.Game.ServiceRosterAsync
import Vegas.Pending.ReactiveCanonicalDecision

/-! # Protection at every roster activation

The asynchronous contract guarantees an owner a timely opportunity. The
reserved roster has a stronger property: every activation at which its owned
event is ready lies inside the protected inclusion window. The argument holds
at every legal history, including histories generated by arbitrary deviations.
-/

noncomputable section

namespace Vegas

open SourceProgram Interaction EventGraphRuntime

variable {Player : Type} [DecidableEq Player]
  {L : IExpr} [IExpr.ResultTypes L]

/-- Every ready owner activation on the roster calendar has sufficient time
for its reserved inclusion, independently of activation coverage. -/
theorem rosterScheduler_activation_fits (setup : Setup (Player := Player) (L := L))
    (leaks : MessageNetwork.ObservationRule Player (WitnessedPacket (graph setup)))
    (rosters : (graph setup).EventId → List Player)
    (network : (runtime setup).NetworkPolicy leaks)
    {control : (application setup leaks).Control}
    (trace : ((application setup leaks).protocol (initialLaw setup)
      (rosterPlan setup rosters).length (rosterScheduler setup leaks rosters network)).Trace
        (some control))
    (event : (graph setup).EventId) (owner : Player)
    (active : control.actor = some owner)
    (owned : (graph setup).actor? event = some owner)
    (readyView : control.execution.application.publicView.EventReady event) :
    control.execution.application.publicView.InclusionFitsDeadline (runtime setup)
      (fun _ => 0) event := by
  have ready := (State.publicView_eventReady _ event).mp readyView
  rcases rosterReach_history setup leaks rosters network trace with
    ⟨current, offset, phase⟩ | ⟨_, idle, _⟩
  · obtain ⟨_, early⟩ := phase.activation owner active
    have ordered := phase.ordered_of_le early
    have same : event = current :=
      Fin.ext ((ready_iff_rank setup _ current.val ordered event).mp ready)
    subst current
    obtain ⟨⟨inputs, invariant⟩, _⟩ := roster_trace_facts setup leaks _ _ trace
    obtain ⟨entered, activated⟩ := invariant.activatedAt_eq_some_of_ready_actor event ready
      (by simp [owned])
    have bounds := phase.entered ordered entered activated
    have clockEq := phase.clock
    change match control.execution.application.activatedAt event with
      | none => False
      | some entered => control.execution.application.clock - entered + 0 < event.val + 1
    rw [activated]
    omega
  · rw [idle] at active
    cases active

end Vegas
