/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import GameTheoryExtensionsTests.CoalescingEquilibrium
import GameTheoryExtensionsTests.CorrelatedSequentialGap
import GameTheoryExtensionsTests.ComponentCommunication
import GameTheoryExtensionsTests.CoupledIncentives
import GameTheoryExtensionsTests.IncentiveSimulation
import GameTheoryExtensionsTests.PassageRestrictionExtension
import GameTheoryExtensionsTests.ProportionalBeliefTransport
import GameTheoryExtensionsTests.ContinuationDecision
import GameTheoryExtensionsTests.ObservationRequirement
import GameTheoryExtensionsTests.ActionRestriction
import GameTheoryExtensionsTests.ConsistencyCompletion
import GameTheoryExtensionsTests.IncentiveCone
import GameTheoryExtensionsTests.InducedInformation
import GameTheoryExtensionsTests.OffPathDisclosureLaws
import GameTheoryExtensionsTests.ObservationQuotients
import GameTheoryExtensionsTests.ObservationErasure
import GameTheoryExtensionsTests.ObservationPayoff
import GameTheoryExtensionsTests.PreservationContracts
import GameTheoryExtensionsTests.PrivateStrategy
import GameTheoryExtensionsTests.SequentialCredibility
import GameTheoryExtensionsTests.SequentialDisclosure
import GameTheoryExtensionsTests.AmbientEnforcement
import GameTheoryExtensionsTests.AmbientEnforcementInformation
import GameTheoryExtensionsTests.AmbientEnforcementSource
import GameTheoryExtensionsTests.AmbientEnforcementAssessment
import GameTheoryExtensionsTests.AmbientEnforcementEquilibrium
import GameTheoryExtensionsTests.AmbientEnforcementThreshold
import GameTheoryExtensionsTests.ForcedFailureEnforcement
import GameTheoryExtensionsTests.EnforcementSynthesis
import GameTheoryExtensionsTests.RestrictionEnforcement
import GameTheoryExtensionsTests.DecisionRecall
import GameTheoryExtensionsTests.MonitoredSignaling
import GameTheoryExtensionsTests.PendingChoice
import GameTheoryExtensionsTests.RegularChoice
import GameTheoryExtensionsTests.ZeroSumOutcomeLaws

/-! # Regression tests for reusable game-theoretic extensions -/
