import GameTheory.Languages.ElectronicMailGame

/-!
# In-flight observations and common belief

Vegas-facing names for the finite electronic-mail information pattern used to
model unreliable in-flight observations.

The point is deliberately narrow: an in-flight observation is not a public
correlation device.  At the delivered endpoint, the payoff-relevant pending
event is mutually believed, but it is not common `p`-belief above the
one-half threshold.  Consequently, any model-specific coordination-survival
argument that requires the common-`p`-belief certificate from
`GameTheory.Concepts.ApproximateCommonKnowledge` cannot apply at that endpoint.
-/

namespace Vegas
namespace Examples
namespace InFlightCommonBelief

open GameTheory
open GameTheory.ElectronicMailGame

noncomputable section

/-- Endpoint worlds of the finite unreliable in-flight observation pattern. -/
abbrev InFlightWorld := EmailWorld

/-- Private views of the in-flight observation. -/
abbrev InFlightView := EmailView

/-- Coordination actions in the in-flight worked example. -/
abbrev InFlightAction := EmailAction

/-- The real-valued prior over in-flight endpoint worlds. -/
abbrev inFlightWorldPrior : InFlightWorld → ℝ :=
  worldPrior

/-- Player partitions generated by their in-flight observations. -/
abbrev inFlightPartition : Bool → InfoPartition InFlightWorld :=
  emailPartition

/-- The payoff-relevant event: the pending signal was actually sent. -/
abbrev pendingEvent : Finset InFlightWorld :=
  attackStateEvent

/-- The endpoint where both players have seen the in-flight observation. -/
abbrev deliveredEndpoint : InFlightWorld :=
  EmailWorld.bothConfirmed

/-- Bayesian coordination game induced by the unreliable in-flight views. -/
abbrev inFlightCoordinationGame : BayesianGame Bool :=
  game

/-- The tempting rule: coordinate exactly when the in-flight item is visible. -/
abbrev actOnVisibleInFlight : inFlightCoordinationGame.BProfile :=
  attackOnMessage

/-- At the delivered endpoint, the pending event is mutually `p`-believed for
every threshold at most one. -/
theorem deliveredEndpoint_mem_mutualPBelief_pending {p : ℝ} (hp : p ≤ 1) :
    deliveredEndpoint ∈
      mutualPBelief inFlightWorldPrior inFlightPartition p pendingEvent := by
  simpa [deliveredEndpoint, inFlightWorldPrior, inFlightPartition, pendingEvent]
    using bothConfirmed_mem_mutualPBelief_attackStateEvent hp

/-- But for thresholds above one half, the same endpoint does not make the
pending event common `p`-belief. -/
theorem deliveredEndpoint_not_commonPBelief_pending_of_half_lt
    {p : ℝ} (hp : (1 / 2 : ℝ) < p) :
    ¬ CommonPBeliefAt inFlightWorldPrior inFlightPartition p pendingEvent
        deliveredEndpoint := by
  simpa [deliveredEndpoint, inFlightWorldPrior, inFlightPartition, pendingEvent]
    using not_commonPBeliefAt_attackStateEvent_bothConfirmed_of_half_lt hp

/-- Mutual high belief and common high belief diverge in the in-flight model. -/
theorem deliveredEndpoint_mutual_not_commonPBelief_pending
    {p : ℝ} (hp_le : p ≤ 1) (hp_half : (1 / 2 : ℝ) < p) :
    deliveredEndpoint ∈
        mutualPBelief inFlightWorldPrior inFlightPartition p pendingEvent ∧
      ¬ CommonPBeliefAt inFlightWorldPrior inFlightPartition p pendingEvent
        deliveredEndpoint := by
  exact
    ⟨deliveredEndpoint_mem_mutualPBelief_pending hp_le,
      deliveredEndpoint_not_commonPBelief_pending_of_half_lt hp_half⟩

/-- Coordination-on-visible-in-flight is not Bayes-Nash in the finite
unreliable-observation game. -/
theorem actOnVisibleInFlight_not_bayesNash :
    ¬ inFlightCoordinationGame.BayesNash actOnVisibleInFlight := by
  simpa [inFlightCoordinationGame, actOnVisibleInFlight]
    using attackOnMessage_not_bayesNash

/-- If a concrete payoff/rationality argument says that a surviving
coordination state must provide the standard common-`p`-belief certificate,
then the delivered in-flight endpoint cannot be such a surviving state for
thresholds above one half. -/
theorem no_survival_certificate_at_deliveredEndpoint
    {p : ℝ} (hp : (1 / 2 : ℝ) < p)
    {Survives : InFlightWorld → Prop}
    (hcert :
      ∀ s, Survives s →
        CommonPBeliefCertificate inFlightWorldPrior inFlightPartition p
          pendingEvent s) :
    ¬ Survives deliveredEndpoint := by
  intro hsurvives
  have hcommon :
      CommonPBeliefAt inFlightWorldPrior inFlightPartition p pendingEvent
        deliveredEndpoint :=
    survives_only_if_commonPBelief_certificate
      (μ := inFlightWorldPrior) (P := inFlightPartition)
      (p := p) (E := pendingEvent) (Survives := Survives)
      hcert hsurvives
  exact deliveredEndpoint_not_commonPBelief_pending_of_half_lt hp hcommon

end

end InFlightCommonBelief
end Examples
end Vegas
