/-
Copyright (c) 2026 VegasCore contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: VegasCore contributors
-/

import Vegas.Machine.Contract.ClassicalEVMStorage
import Vegas.Machine.Contract.Imperative

/-!
# Classical EVM handler inventory

This pass routes every graph node to the deterministic classical ABI and
lowers its readiness requirements to the certified total EVM storage layout.
Commit and reveal nodes have one route; a sample node has a request route and
a callback route because classical chance is a two-transaction protocol.

The resulting IR still retains typed node code for expression-specific
lowering. Its structural checks, however, are already concrete EVM storage
reads, and acceptance over an encoded snapshot is proved exactly equivalent to
event-graph readiness.
-/

namespace Vegas.Machine.Contract.EVM

open EventGraph

noncomputable section

variable {Player : Type} [DecidableEq Player]
variable {L : IExpr} {program : Program Player L}

/-- Deterministic classical entry point responsible for one node operation. -/
inductive ClassicalRoute where
  | player
  | reveal
  | sampleRequest
  | oracleCallback
deriving DecidableEq

/-- Entry-point routes generated by one node's semantic kind. -/
def classicalRoutes : NodeSem Player L → List ClassicalRoute
  | .commit _ _ => [.player]
  | .reveal _ => [.reveal]
  | .sample _ => [.sampleRequest, .oracleCallback]

/-- One completion-bit assertion in the total EVM layout. -/
structure ClassicalStorageCheck where
  slot : Nat
  expected : Bool
deriving DecidableEq

namespace ClassicalStorageCheck

/-- Evaluate a storage assertion, rejecting noncanonical Boolean words. -/
def evaluate (storage : TotalStorage) (check : ClassicalStorageCheck) : Bool :=
  match decodeBool (storage check.slot) with
  | none => false
  | some actual => decide (actual = check.expected)

end ClassicalStorageCheck

/-- Lower one logical readiness requirement to its total EVM completion cell.
-/
def lowerClassicalRequirement
    (requirement : Imperative.Requirement program) : ClassicalStorageCheck :=
  let layout := ClassicalStorageLayout.canonical program
  match requirement with
  | .notCompleted node =>
      { slot := layout.address (.completed node), expected := false }
  | .completed node =>
      { slot := layout.address (.completed node), expected := true }

/-- Concrete ordered EVM checks for one graph node. Replay prevention remains
first, followed by prerequisites in canonical `Finset.toList` order. -/
def classicalChecks (program : Program Player L)
    (node : Fin program.graph.nodeCount) : List ClassicalStorageCheck :=
  (Imperative.requirements program node).map lowerClassicalRequirement

/-- Lowering one readiness requirement to total EVM storage preserves its
semantic truth value. -/
theorem lowerClassicalRequirement_correct
    (codec : StorageCodec program) (words : WireCodec codec.Word Word)
    (nodes : WireCodec (Fin program.graph.nodeCount) Word)
    (cfg : Config program.graph)
    (pending : Option (Fin program.graph.nodeCount))
    (requirement : Imperative.Requirement program) :
    ClassicalStorageCheck.evaluate
        (encodeClassicalSnapshot codec words nodes
          { graph := StateSnapshot.ofConfig cfg, pending := pending })
        (lowerClassicalRequirement requirement) =
      Imperative.Requirement.evaluate cfg requirement := by
  cases requirement with
  | notCompleted node =>
      unfold ClassicalStorageCheck.evaluate lowerClassicalRequirement
      dsimp only
      rw [encodeClassicalSnapshot_completed, decodeBool_encodeBool]
      simp [Imperative.Requirement.evaluate]
  | completed node =>
      unfold ClassicalStorageCheck.evaluate lowerClassicalRequirement
      dsimp only
      rw [encodeClassicalSnapshot_completed, decodeBool_encodeBool]
      simp [Imperative.Requirement.evaluate]

/-- Ordered concrete EVM completion checks accept exactly ready source nodes.
-/
theorem classicalChecks_accept_iff_ready
    (codec : StorageCodec program) (words : WireCodec codec.Word Word)
    (nodes : WireCodec (Fin program.graph.nodeCount) Word)
    (cfg : Config program.graph)
    (pending : Option (Fin program.graph.nodeCount))
    (node : Fin program.graph.nodeCount) :
    Imperative.evaluateAll
        (ClassicalStorageCheck.evaluate
          (encodeClassicalSnapshot codec words nodes
            { graph := StateSnapshot.ofConfig cfg, pending := pending }))
        (classicalChecks program node) =
      decide (Ready program.graph cfg node) := by
  unfold classicalChecks
  unfold Imperative.evaluateAll
  rw [List.all_map]
  have hevaluate :
      (fun requirement =>
        ClassicalStorageCheck.evaluate
          (encodeClassicalSnapshot codec words nodes
            { graph := StateSnapshot.ofConfig cfg, pending := pending })
          (lowerClassicalRequirement requirement)) =
        Imperative.Requirement.evaluate cfg := by
    funext requirement
    exact lowerClassicalRequirement_correct codec words nodes cfg pending
      requirement
  change (Imperative.requirements program node).all
      (fun requirement =>
        ClassicalStorageCheck.evaluate
          (encodeClassicalSnapshot codec words nodes
            { graph := StateSnapshot.ofConfig cfg, pending := pending })
          (lowerClassicalRequirement requirement)) = _
  rw [hevaluate]
  exact Imperative.evaluateAll_requirements cfg node

/-- One routed node plan for handler-specific lowering. -/
structure ClassicalActionIR (program : Program Player L) where
  node : Fin program.graph.nodeCount
  route : ClassicalRoute
  routed : route ∈ classicalRoutes (program.graph.nodeRow node).sem
  checks : List ClassicalStorageCheck
  valueSlot : Nat
  presenceSlot : Nat
  completionSlot : Nat
  checks_eq : checks = classicalChecks program node
  valueSlot_eq : valueSlot =
    (ClassicalStorageLayout.canonical program).address
      (.fieldValue
        ⟨program.graph.nodeTarget node,
          StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
  presenceSlot_eq : presenceSlot =
    (ClassicalStorageLayout.canonical program).address
      (.fieldPresent
        ⟨program.graph.nodeTarget node,
          StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
  completionSlot_eq : completionSlot =
    (ClassicalStorageLayout.canonical program).address (.completed node)

/-- Compile one graph node into all deterministic routes that implement it. -/
def compileClassicalActions (program : Program Player L)
    (node : Fin program.graph.nodeCount) : List (ClassicalActionIR program) :=
  let layout := ClassicalStorageLayout.canonical program
  (classicalRoutes (program.graph.nodeRow node).sem).attach.map fun route =>
    { node := node
      route := route.1
      routed := route.2
      checks := classicalChecks program node
      valueSlot := layout.address
        (.fieldValue
          ⟨program.graph.nodeTarget node,
            StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
      presenceSlot := layout.address
        (.fieldPresent
          ⟨program.graph.nodeTarget node,
            StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
      completionSlot := layout.address (.completed node)
      checks_eq := rfl
      valueSlot_eq := rfl
      presenceSlot_eq := rfl
      completionSlot_eq := rfl }

/-- Complete classical EVM handler inventory. -/
structure ClassicalContractIR (program : Program Player L) where
  storageSize : Nat
  actions : List (ClassicalActionIR program)

/-- Compile every graph node in stable order to its classical handler routes.
-/
def compileClassicalIR (program : Program Player L) :
    ClassicalContractIR program where
  storageSize := (ClassicalStorageLayout.canonical program).slotCount
  actions := program.graph.nodeOrder.flatMap (compileClassicalActions program)

/-- Every generated action retains exactly the concrete checks of its node. -/
@[simp] theorem compileClassicalActions_checks
    (node : Fin program.graph.nodeCount)
    (action : ClassicalActionIR program)
    (_hmem : action ∈ compileClassicalActions program node) :
    action.checks = classicalChecks program action.node := by
  exact action.checks_eq

/-- Every commit node has its player handler plan. -/
theorem player_action_mem_of_commit
    (node : Fin program.graph.nodeCount) (who : Player) (guard : EventGuard L)
    (hsem : (program.graph.nodeRow node).sem = .commit who guard) :
    ∃ action ∈ (compileClassicalIR program).actions,
      action.node = node ∧ action.route = .player := by
  let action : ClassicalActionIR program :=
    { node := node
      route := .player
      routed := by simp [hsem, classicalRoutes]
      checks := classicalChecks program node
      valueSlot := (ClassicalStorageLayout.canonical program).address
        (.fieldValue
          ⟨program.graph.nodeTarget node,
            StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
      presenceSlot := (ClassicalStorageLayout.canonical program).address
        (.fieldPresent
          ⟨program.graph.nodeTarget node,
            StateSnapshot.nodeTarget_lt_fieldCount program.graph node⟩)
      completionSlot := (ClassicalStorageLayout.canonical program).address
        (.completed node)
      checks_eq := rfl
      valueSlot_eq := rfl
      presenceSlot_eq := rfl
      completionSlot_eq := rfl }
  refine ⟨action, ?_, rfl, rfl⟩
  simp [compileClassicalIR, compileClassicalActions, Graph.mem_nodeOrder,
    action, hsem, classicalRoutes]

/-- The three cells written by a successful routed action are pairwise
distinct. -/
theorem ClassicalActionIR.writeSlots_pairwise
    (action : ClassicalActionIR program) :
    action.valueSlot ≠ action.presenceSlot ∧
      action.valueSlot ≠ action.completionSlot ∧
      action.presenceSlot ≠ action.completionSlot := by
  rw [action.valueSlot_eq, action.presenceSlot_eq, action.completionSlot_eq]
  have injective := (ClassicalStorageLayout.canonical program).injective
  constructor
  · intro heq
    have := injective heq
    cases this
  · constructor
    · intro heq
      have := injective heq
      cases this
    · intro heq
      have := injective heq
      cases this

end

end Vegas.Machine.Contract.EVM
