/-
Copyright (c) 2026 VegasCore contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: VegasCore contributors
-/

import Vegas.Compile.Compiler
import Vegas.Compile.ConditionalExecution
import Vegas.Compile.ConditionalPublicationSite
import Vegas.Compile.ConditionalOpeningController
import Vegas.Compile.ConditionalPublication
import Vegas.Compile.ConditionalResolution
import Vegas.Compile.PublicChoice
import Vegas.Compile.PublicChoiceSite
import Vegas.Compile.PublicChoiceExecution
import Vegas.Compile.PublicChoiceValidation
import Vegas.Compile.PublicChoiceController
import Vegas.Compile.ApplicationImage
import Vegas.Compile.ApplicationImageSamples
import Vegas.Compile.ApplicationSampleLaw
import Vegas.Compile.ApplicationImageBindings
import Vegas.Compile.ApplicationImagePrivacy
import Vegas.Compile.WindowedPrivacy
import Vegas.Compile.WindowedPolicyPrivacy
import Vegas.Compile.WindowedReplayPrivacy
import Vegas.Compile.WindowedMessageOrigins
import Vegas.Compile.ApplicationPolicyAddresses
import Vegas.Compile.ApplicationBindingOrigins
import Vegas.Compile.ApplicationAcceptedPrefix
import Vegas.Compile.ApplicationImageInvariants
import Vegas.Compile.ApplicationPlan
import Vegas.Compile.ApplicationService
import Vegas.Compile.ApplicationPlanCoverage
import Vegas.Compile.ApplicationPlanAllocation
import Vegas.Compile.ApplicationPlanOrigin
import Vegas.Compile.ApplicationGuardSoundness
import Vegas.Compile.BindingResolution
import Vegas.Compile.ConditionalOpeningValidation
import Vegas.Compile.ConditionalImage
import Vegas.Compile.ConditionalImageRefinement
import Vegas.Compile.PublicChoiceImage
import Vegas.Compile.SampleImage
import Vegas.Compile.SampleImageRefinement
import Vegas.Compile.ApplicationImageController
import Vegas.Compile.ConditionalImageController
import Vegas.Compile.ApplicationImageReadout
import Vegas.Compile.ApplicationImageRegistration
import Vegas.Compile.ApplicationImageBindingInclusion
import Vegas.Compile.ApplicationImageProvenance
import Vegas.Compile.ApplicationImageCoverage
import Vegas.Compile.ApplicationImageReadoutAvailability
import Vegas.Compile.SourceReadoutAvailability
import Vegas.Compile.BindingImageController
import Vegas.Compile.BindingImageExecution
import Vegas.Compile.ApplicationSampleExecution
import Vegas.Compile.PublicChoiceImageExecution
import Vegas.Compile.PublicChoicePhaseExecution
import Vegas.Compile.PublicChoiceSourceCoupling
import Vegas.Compile.BindingSourceCoupling
import Vegas.Compile.BindingPhaseExecution
import Vegas.Compile.ConditionalSourceCoupling
import Vegas.Compile.ConditionalExpirationSourceCoupling
import Vegas.Compile.ConditionalSnapshot
import Vegas.Compile.ConditionalPhaseExecution
import Vegas.Compile.ApplicationPolicy
import Vegas.Compile.ApplicationProfileContinuation
import Vegas.Compile.ApplicationContinuationReadout
import Vegas.Compile.ApplicationInitialReads
import Vegas.Compile.ApplicationForwardCheckpoint
import Vegas.Compile.ApplicationSampleForward
import Vegas.Compile.ApplicationBindingForward
import Vegas.Compile.ApplicationPublicChoiceForward
import Vegas.Compile.ApplicationOwnerPhase
import Vegas.Compile.ApplicationConditionalOwner
import Vegas.Compile.ApplicationConditionalForward
import Vegas.Compile.ApplicationForwardLaw
import Vegas.Compile.ApplicationChoiceTimeouts
import Vegas.Compile.ApplicationTimeoutForwardLaw
import Vegas.Compile.PublicResolution
import Vegas.Compile.ApplicationBindingDefault
import Vegas.Compile.ApplicationBindingTimeouts
import Vegas.Compile.BindingTimeoutCompilation
import Vegas.Compile.ApplicationBindingTimeoutRefinement
import Vegas.Compile.PublicChoiceResolution
import Vegas.Compile.ApplicationMessageRequirement
import Vegas.Compile.ApplicationWithholding
import Vegas.Compile.ApplicationPolicyFreshness
import Vegas.Compile.ApplicationCacheSeparation
import Vegas.Compile.ApplicationPolicyCache
import Vegas.Compile.ApplicationPhaseCaches
import Vegas.Compile.ApplicationPolicyLocality
import Vegas.Compile.ApplicationPolicyBindings
import Vegas.Compile.ApplicationPolicyProvenance
import Vegas.Compile.ApplicationImageRefinement
import Vegas.Compile.BindingImageRefinement
import Vegas.Compile.ApplicationImageOutcome
import Vegas.Compile.ApplicationImageStateRefinement
import Vegas.Compile.PublicationStateRefinement
import Vegas.Compile.ApplicationPlanRefinement
import Vegas.Compile.ApplicationTimeoutRefinement
import Vegas.Compile.ApplicationSourceOutcome
import Vegas.Compile.ApplicationPlanOutcome
import Vegas.Compile.SourceChoiceController
import Vegas.Compile.PublicGuard
import Vegas.Compile.DecisionSite
import Vegas.Compile.FieldMap
import Vegas.Compile.SourceAdequacy
import Vegas.Compile.SourceOrder
import Vegas.Compile.SourceInformation
import Vegas.Compile.PolicyInformation
import Vegas.Compile.SourceLaw
import Vegas.Compile.SourceExecution
import Vegas.Compile.SourceExecutionGraph
import Vegas.Compile.SourceExecutionLaw
import Vegas.Compile.ApplicationOrder
import Vegas.Compile.ApplicationOrderTimeouts
import Vegas.Compile.ApplicationOrderPrefix
import Vegas.Compile.ApplicationCompletion
import Vegas.Compile.ApplicationDeadlines
import Vegas.Compile.ApplicationPlanDeadlines
import Vegas.Compile.ApplicationDeadlineInvariants
import Vegas.Compile.ApplicationImageClock
import Vegas.Compile.WindowedApplication
import Vegas.Compile.WindowedExpiry
import Vegas.Compile.WindowedExpiryResolution
import Vegas.Compile.WindowedRelayResolution
import Vegas.Compile.WindowedExpiryService
import Vegas.Compile.WindowedBlockService
import Vegas.Compile.WindowedBlockAlignment
import Vegas.Compile.WindowedBlockDeterminism
import Vegas.Compile.WindowedBlockPredraw
import Vegas.Compile.WindowedBlockIsolation
import Vegas.Compile.WindowedActivationFreshness
import Vegas.Compile.WindowedBlockSample
import Vegas.Compile.WindowedBlockSettlement
import Vegas.Compile.WindowedBlockProgress
import Vegas.Compile.WindowedBindingSettlement
import Vegas.Compile.WindowedBindingBlock
import Vegas.Compile.WindowedPublicChoiceBlock
import Vegas.Compile.WindowedCheckpoint
import Vegas.Compile.WindowedBindingCheckpoint
import Vegas.Compile.WindowedSampleCaches
import Vegas.Compile.WindowedBlockCaches
import Vegas.Compile.WindowedSampleCheckpoint
import Vegas.Compile.WindowedForeignProvenance
import Vegas.Compile.WindowedBindingProvenance
import Vegas.Compile.WindowedBlockProvenance
import Vegas.Compile.WindowedContinuationReadout
import Vegas.Compile.WindowedConditionalOwner
import Vegas.Compile.WindowedBindingOwner
import Vegas.Compile.WindowedPublicChoiceOwner
import Vegas.Compile.WindowedReadoutProjection
import Vegas.Compile.WindowedBlockResolution
import Vegas.Compile.ApplicationRelayHistory
import Vegas.Compile.WindowedProjection
import Vegas.Compile.WindowedExecutionProjection
import Vegas.Compile.WindowedPolicyProjection
import Vegas.Compile.ApplicationDeadlineIndependence
import Vegas.Compile.ApplicationDeadlinePolicies
import Vegas.Compile.WindowedApplicationDeadline
import Vegas.Compile.WindowedApplicationInvariants
import Vegas.Compile.WindowedSourceSafety
import Vegas.Compile.WindowedApplicationCoverage
import Vegas.Compile.WindowedForwardLaw
import Vegas.Compile.WindowedSampleLaw
import Vegas.Compile.ApplicationPlanSampleLaw
import Vegas.Compile.WindowedExpiryStability
import Vegas.Compile.ApplicationResolvedBindings
import Vegas.Compile.ApplicationSampleFrames
import Vegas.Compile.ApplicationOrderPhase
import Vegas.Compile.ApplicationOrderCheckpoint
import Vegas.Compile.ApplicationOrderRefinement
import Vegas.Compile.SourceExecutionOutcome
import Vegas.Compile.SourceOutcome
import Vegas.Compile.SourceObservation
import Vegas.Compile.SourcePolicy
import Vegas.Compile.SourceBacktranslation
import Vegas.Compile.SourceStrategy
import Vegas.Compile.Machine
import Vegas.Compile.SealedMessages
import Vegas.Compile.SealedDecode
import Vegas.Compile.SealedExecution
import Vegas.Compile.SealedRules
import Vegas.Compile.SealedDecodeLaws
import Vegas.Compile.SealedRefinement
import Vegas.Compile.SealedSource
import Vegas.Compile.SealedTimeoutRefinement

/-!
# Compilation: checked Vegas programs and runtime components

`Compiler` lowers a `GraphProgram` / `WFProgram` into a canonical
`EventGraph.Graph` with typed fields, causal dependencies, guarded commit
nodes, exact finite laws, and terminal payoff projections.
Structural application plans generate binding, chance, and publication instructions.
Arbitrary supported public-message executions refine reachable graph states;
completed runs have the public outcome of a written-order source execution.
The generated serial reference execution finishes with the independent source
public-outcome law, under explicit initial-read and binding-origin conditions.
Strategic correspondence and progress under arbitrary deviations remain separate obligations.
-/
