/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.Game.RevealServiceRosterContinuation
import Vegas.Game.ServiceRosterLocalEvaluation
import Vegas.Game.RevealServiceRosterHarmless
import Vegas.Game.RevealServiceRosterHarmlessComparison
import Vegas.Game.RevealServiceRosterInitialized
import Vegas.Game.RevealServiceRosterOwnerHistoryValue
import Vegas.Game.RevealServiceRosterOwnerHazard
import Vegas.Game.RevealServiceRosterOwnerValue
import Vegas.Game.RevealServiceRosterOwnerSite
import Vegas.Game.RevealServiceRosterOwnerIncentives
import Vegas.Game.RevealServiceRosterEquilibrium
import Vegas.Game.RevealServiceRosterCompilation
import Vegas.Game.RevealServiceRosterSitePosition
import Vegas.Game.RevealServiceRosterTiming
import Vegas.Game.RevealServiceRosterWindowSource
import Vegas.Game.RevealSourceContinuation
import Vegas.Game.RevealSourcePayoffBounds
import Vegas.Game.SourceServiceAdmission
import Vegas.Game.SourceServiceMenu
import Vegas.Game.SourceServiceCheckpoint
import Vegas.Game.SourceServiceBindingRoster
import Vegas.Game.SourceServiceBindingPhase
import Vegas.Game.SourceServiceTimedPolicy
import Vegas.Game.SourceServiceTimedBinding
import Vegas.Game.SourceServiceActiveBindingLaw
import Vegas.Game.SourceServiceActiveBindingCheckpoint
import Vegas.Game.SourceServiceTimedDisclosure
import Vegas.Game.SourceServiceTimedSample
import Vegas.Game.SourceServiceTimedCheckpoint
import Vegas.Game.SourceServiceTimedBindingCheckpoint
import Vegas.Game.SourceServiceTimedSupport
import Vegas.Game.SourceServiceTimedAdmissibility
import Vegas.Game.SourceServiceTimedMixing
import Vegas.Game.SourceServiceTimedLaw
import Vegas.Game.SourceServiceTimedContinuation
import Vegas.Game.SourceServiceTimedReachability
import Vegas.Game.SourceServiceLocalComparison
import Vegas.Game.SourceServiceCompletion
import Vegas.Game.SourceServiceContinuationBridge
import Vegas.Game.SourceServiceFiniteness
import Vegas.Game.SourceServiceTurnPolicy
import Vegas.Game.SourceServiceBindingSource
import Vegas.Game.SourceServiceForeignComparison
import Vegas.Game.SourceServiceForeignDisclosure
import Vegas.Game.SourceServiceSiteKind
import Vegas.Game.SourceServiceOwnerComparison
import Vegas.Game.SourceServiceUnsentBinding
import Vegas.Game.SourceServiceAbsentOpening
import Vegas.Game.SourceServiceAvailableOpening
import Vegas.Game.SourceServiceEquilibrium
import Vegas.Game.SourceServiceCompilation
import Vegas.Game.SourceServiceHarmlessContinuation
import Vegas.Game.SourceServiceSampleComparison
import Vegas.Game.SourceServiceRecordedContinuation
import Vegas.Game.SourceServiceBindingContinuation
import Vegas.Game.SourceServiceTimingPosterior
import Vegas.Game.SourceServiceChoiceSupport
import Vegas.Game.SourceServiceLocalSupport
import Vegas.Game.SourceChoiceCompletion
import Vegas.Game.SourceServiceBoundary
import Vegas.Game.SourceServiceBindingSupport
import Vegas.Game.SourceServiceBindingBoundary
import Vegas.Game.SourceServiceSampleBoundary
import Vegas.Game.SourceServiceResolutionBoundary
import Vegas.Game.SourceServicePrefixSupport
import Vegas.Game.SourceServiceDecisionSupport
import Vegas.Game.SourceServiceDecisionResources
import Vegas.Game.SourceServicePhaseStart
import Vegas.Game.SourceServiceInclusionSupport
import Vegas.Game.SourceServiceConformance
import Vegas.Game.SourceServiceTrafficSound
import Vegas.Game.SourceServiceOmission
import Vegas.Game.SourceServiceAudit
import Vegas.Game.SourceServiceRepairSettlement
import Vegas.Game.ServicePayoffBounds
import Vegas.Game.SourceServiceEvidence
import Vegas.Game.SourceServiceFinalBindingRepair
import Vegas.Game.SourceServiceFirstBindingBlock
import Vegas.Game.SourceServiceRepairForeignWindow
import Vegas.Game.SourceServiceRepairOpportunity
import Vegas.Game.SourceServiceBindingWaiting
import Vegas.Game.SourceServiceStoppedBindingWindow
import Vegas.Game.SourceServiceOffTurnWindow
import Vegas.Game.SourceServiceSampleRepair
import Vegas.Game.SourceServiceResolutionRepair
import Vegas.Game.SourceServiceResolutionWindow
import Vegas.Game.SourceServiceResolutionBlock
import Vegas.Game.SourceServiceReservedRepair
import Vegas.Game.SourceServiceForeignBindingRepair
import Vegas.Game.SourceServiceForeignBindingBlock
import Vegas.Game.SourceServiceProgramRepair
import Vegas.Game.SourceServiceEventRepair
import Vegas.Game.SourceServiceRemainingRepair
import Vegas.Game.SourceServiceActiveResolutionRepair
import Vegas.Game.SourceServiceActiveOffTurnRepair
import Vegas.Game.SourceServiceActiveBlockRepair
import Vegas.Game.SourceServiceActiveRepeatedBindingRepair
import Vegas.Game.SourceServiceActiveRepair
import Vegas.Game.SourceServiceEvaluatorRepair
import Vegas.Game.SourceServiceContinuationComparison
import Vegas.Game.SourceServiceRestrictionExtension
import Vegas.Game.SourceServiceRawExtension
import Vegas.Game.SourceServiceSubmittedBinding
import Vegas.Game.SourceServiceRepeatedWindow
import Vegas.Game.SourceServiceImplementationSegment
import Vegas.Game.SourceServiceRepeatedBlock
import Vegas.Game.SourceServiceExecution
import Vegas.Game.SourceServiceCompiledExecution
import Vegas.Game.SourceServicePhaseLaw
import Vegas.Game.SourceServiceLaw
import Vegas.Game.SourceServicePosterior
import Vegas.Game.SourceServiceCoverage
import Vegas.Game.SourceServiceFactorization
import Vegas.Game.SourceServiceDisclosureFactorization
import Vegas.Game.SourceServiceSampleFactorization
import Vegas.Game.SourceServiceRosterPolicy
import Vegas.Game.SourceServiceWaiting
import Vegas.Game.SourceServiceDisclosure
import Vegas.Game.SourceServiceDisclosurePosterior
import Vegas.Game.SourceServiceDisclosureMemory
import Vegas.Game.SourceServiceDisclosurePhase
import Vegas.Game.SourceServiceSettlement
import Vegas.Game.SourceServicePrefix
import Vegas.Game.SourceServicePrefixInformation
import Vegas.Game.SourceServicePrefixFactorization
import Vegas.Game.SourceServicePrefixPosterior
import Vegas.Game.SourceServiceBayes
import Vegas.Game.SourceServiceAssessment
import Vegas.Game.RevealServiceRosterOwnerComparison
import Vegas.Game.RevealServiceRosterPhase
import Vegas.Game.RevealServiceRosterWindowValue
import Vegas.Game.PurificationEdge
import Vegas.Game.DisclosureForeign
import Vegas.Game.DisclosureProfileComparison
import Vegas.Game.SourceBayes
import Vegas.Game.DisclosureAssessment
import Vegas.Game.BindingRepairOpening
import Vegas.Game.BindingRepairReadout
import Vegas.Game.SourceServicePolicy
import Vegas.Game.SourceServiceStep
import Vegas.Game.SourceServiceBinding
import Vegas.Game.ServiceRosterEvaluation
import Vegas.Game.RevealServiceRosterEvidence
import Vegas.Game.RevealServiceRosterOwnerNoise
import Vegas.Game.RevealServiceRosterOwnerPosterior
import Vegas.Game.RevealServiceRosterBayes
import Vegas.Game.RevealServiceRosterTraffic
import Vegas.Game.RevealServiceRosterDeparture
import Vegas.Game.RevealServiceRosterTrafficSound
import Vegas.Game.RevealServiceRosterChoiceEvidence
import Vegas.Game.RevealServiceRosterAudit
import Vegas.Game.RevealServiceRosterWindowContinuation
import Vegas.Game.ValueBindingEdge
import Vegas.Game.EventScheduling
import Vegas.Game.EventCompilation
import Vegas.Game.EventServiceEdge
import Vegas.Game.EventMessages
import Vegas.Game.ReactiveCompilation
import Vegas.Game.RevealService
import Vegas.Game.RevealServiceActions
import Vegas.Game.RevealServiceBounds
import Vegas.Game.RevealServiceClock
import Vegas.Game.RevealServiceCompletion
import Vegas.Game.RevealServiceBlock
import Vegas.Game.RevealServiceCalendarState
import Vegas.Game.RevealServiceCheckpoint
import Vegas.Game.RevealServiceCollection
import Vegas.Game.RevealServiceExecution
import Vegas.Game.RevealServiceLaw
import Vegas.Game.RevealServicePrefix
import Vegas.Game.RevealServicePrefixLaw
import Vegas.Game.RevealServicePrefixSupport
import Vegas.Game.RevealServicePrefixInformation
import Vegas.Game.RevealServicePrefixHistory
import Vegas.Game.RevealServicePrefixBehavioral
import Vegas.Game.RevealServiceOwnerPrefix
import Vegas.Game.RevealServiceOwnerSupport
import Vegas.Game.RevealServiceOwnerInformation
import Vegas.Game.RevealServiceOwnerSource
import Vegas.Game.RevealServicePrefixChoice
import Vegas.Game.RevealServiceMixing
import Vegas.Game.RevealServiceBayes
import Vegas.Game.RevealServiceConsistency
import Vegas.Game.RevealServicePrefixResponse
import Vegas.Game.RevealServiceOwnerResponse
import Vegas.Game.RevealServiceOwnerLocalLaw
import Vegas.Game.RevealServiceOwnerValue
import Vegas.Game.RevealServiceOwnerIncentives
import Vegas.Game.RevealServiceEquilibrium
import Vegas.Game.RevealServicePrefixEnforcement
import Vegas.Game.RevealServiceOwnerCollection
import Vegas.Game.RevealServiceClean
import Vegas.Game.RevealServiceOrdinaryExtension
import Vegas.Game.RevealServiceDeposits
import Vegas.Game.RevealServiceCompilation
import Vegas.Game.RevealServiceWatcherSupport
import Vegas.Game.RevealServiceReplayMenu
import Vegas.Game.RevealServiceReplayRelation
import Vegas.Game.RevealServiceReplaySource
import Vegas.Game.RevealServiceReplayContinuation
import Vegas.Game.RevealServiceReplayComparison
import Vegas.Game.RevealServiceReplayExtension
import Vegas.Game.RevealServiceReplaySupport
import Vegas.Game.BindingRepairBlock
import Vegas.Game.BindingRepairPrefix
import Vegas.Game.RevealServiceRosterBlock
import Vegas.Game.RevealServiceRosterPolicy
import Vegas.Game.RevealServiceRosterMenu
import Vegas.Game.RevealServiceRosterSupport
import Vegas.Game.RevealServiceRosterCompletion
import Vegas.Game.RevealServiceRosterCheckpoint
import Vegas.Game.ServiceRoster
import Vegas.Game.ServiceRosterAsync
import Vegas.Game.ServiceRosterCounts
import Vegas.Game.RevealServiceRosterPrefixSupport
import Vegas.Game.ServiceRosterClock
import Vegas.Game.ServiceRosterPosition
import Vegas.Game.RevealServiceRosterDecisionSupport
import Vegas.Game.RevealServiceRosterDecisionData
import Vegas.Game.RevealServiceRosterMixing
import Vegas.Game.RevealServiceRosterConvergence
import Vegas.Game.RevealServiceRosterLaw
import Vegas.Game.RevealServiceRosterCoverage
import Vegas.Game.RevealServiceRosterPrefixLaw
import Vegas.Game.RevealServiceRosterCoupling
import Vegas.Game.RevealServiceRosterNoise
import Vegas.Game.RevealServiceRosterPrefixNoise
import Vegas.Game.DisclosurePrefix
import Vegas.Game.DisclosureRetraction
import Vegas.Game.DisclosureBeliefs
import Vegas.Game.DisclosureContinuation
import Vegas.Game.DisclosureRealization
import Vegas.Game.DisclosureComparison
import Vegas.Game.RevealServiceRosterLimit
import Vegas.Game.RevealServiceTraffic
import Vegas.Game.RevealServiceTrafficSound
import Vegas.Game.RevealServiceTrafficDeparture
import Vegas.Game.RevealServiceAuditDeposits
import Vegas.Game.RevealServiceAuditCompilation
import Vegas.Game.RevealServiceSignedCompilation
import Vegas.Game.RevealServicePerturbation
import Vegas.Game.RevealServiceFocalLaw
import Vegas.Game.RevealServiceFocalRecall
import Vegas.Game.RevealServiceOrdinaryComparison
import Vegas.Game.RevealServicePayoffs
import Vegas.Game.RevealServiceSelector
import Vegas.Game.RevealServiceTranscript
import Vegas.Game.RevealServiceEnforcement
import Vegas.Game.RevealServiceCorrespondence
import Vegas.Game.ServiceInformation
import Vegas.Game.ServiceObservation
import Vegas.Game.RevealServiceState
import Vegas.Game.RevealServicePolicy
import Vegas.Game.RevealServiceWatcher
import Vegas.Game.EventMessageStrategic
import Vegas.Game.PendingCompositions
import Vegas.Game.ParameterOutcomes
import Vegas.Game.ZeroSum
import Vegas.Game.SetupSubgame
import Vegas.Game.SourceInformation
import Vegas.Game.SourceContinuation
import Vegas.Game.SourceLocalContinuation
import Vegas.Game.SourceLocalPolicy
import Vegas.Game.SourceStateKernel
import Vegas.Game.SourcePrefixKernel
import Vegas.Game.SourceObservationRecall
import Vegas.Game.BehavioralSubgame

/-! Strategic source-to-graph and graph-to-message correspondence. -/

-- OPEN OBLIGATION: Native subgame-perfect preservation
-- Source continuation laws and conditional SPE transfer and reflection are checked.
-- The reactive protocol has canonical policy correspondence and bounded play.
-- The source policy compiler is defined. Canonical service completion is proved
-- for arbitrary player policies and adaptive network choices.
-- Packet protection, compiler outcome/deviation laws, continuation correspondence,
-- and proper-root coverage remain open. Recovery preserves initialized execution
-- laws, but ReactiveEarlyOpeningSPE proves that the actual recovery compiler fails
-- SPE under a fixed uniform, at-most-once service. Its source policy is honest and
-- SPE. This refutes sufficiency of event-local selection regularity for that compiler;
-- a service or translation contract addressing competition between events is needed.
-- The separate ReactivePendingMenusSource impossibility quantifies over all compilers
-- for its adaptive public scheduler. Neither witness rules out every constrained service.
-- The initial-play Nash/Bayesian theorem does not discharge these obligations.
