import Vegas.Theorems.GraphShape
import Vegas.Theorems.Visibility
import Vegas.Theorems.Progress
import Vegas.Theorems.Frontier
import Vegas.Theorems.Strategy
import Vegas.Theorems.Outcome
import Vegas.Theorems.Realization
import Vegas.Theorems.Backend
import Vegas.Theorems.Nullable

/-!
# Project theorem index

This file re-exports the main Vegas semantic claims under short
project-facing names.

The public theorem surface is organized by topic. Within topics, submodules
separate facts that hold for any `EventGraph` from facts that require the graph
to have been generated by checked `VegasCore` syntax.

Topic modules:

* `Vegas.Theorems.GraphShape`
* `Vegas.Theorems.Visibility`
* `Vegas.Theorems.Progress`
* `Vegas.Theorems.Frontier`
* `Vegas.Theorems.Strategy`
* `Vegas.Theorems.Outcome`
* `Vegas.Theorems.Realization`
* `Vegas.Theorems.Backend`
* `Vegas.Theorems.Nullable`
-/
