/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.Pending.ReactiveDisclosure
import Vegas.Pending.ReactiveFreshCallAcceptance
import Vegas.Pending.ReactiveOpeningWindow
import Vegas.EventGraph.ResolutionProvenance

/-! # Acceptable envelopes generated by actual sampled event decisions -/

noncomputable section

namespace Vegas.EventGraphRuntime

open Interaction EventGraph GameTheory.Math.Probability

variable {Player : Type} [DecidableEq Player]
  {L : IExpr} [IExpr.ResultTypes L] {graph : Vegas.EventGraph Player L}

/-- Every transmitting sampled decision at a ready timely owned event emits an
acceptable fresh call. Its owned private witness is derived from actual binding
provenance; failed disclosure validation instead produces silence. -/
theorem reactiveDecision_emitted_acceptable (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (WitnessedPacket graph))
    (execution : (runtime.reactiveApplication leaks).Execution)
    (valid : execution.application.BindingInvariant)
    (who : Player) (event : graph.EventId)
    (ready : execution.application.config.cut.Ready event)
    (timely : execution.application.WithinDeadline runtime event)
    (actor : graph.actor? event = some who)
    (action : graph.Action event) (material : WitnessedSubmission graph)
    (transmitted : (runtime.reactiveDecision leaks who event action
      (execution.observe (runtime.reactiveApplication leaks) who).application).transmission =
        some material) :
    runtime.freshServiceAcceptable execution.application.publicView
      ⟨(who, execution.network.nextSerial who),
        material.emit ((runtime.reactiveApplication leaks).submit execution.application who
          material)
          who (execution.network.known who)⟩ := by
  let state : State graph := execution.application
  let view : PlayerView graph :=
    (execution.observe (runtime.reactiveApplication leaks) who).application
  cases node : nodeView graph event with
  | sample payload law outputEq codeEq =>
      simp only [reactiveDecision, node] at transmitted
      cases transmitted
  | bind owner payload outputEq codeEq =>
      have ownerEq : owner = who := by
        have actorEq := congrArg EventCode.actor codeEq
        rw [EventCode.actor_cast outputEq (graph.nodes event)] at actorEq
        exact Option.some.inj (actorEq.symm.trans actor)
      subst owner
      simp only [reactiveDecision, node] at transmitted
      obtain ⟨serial, selected, same⟩ := Option.map_eq_some_iff.mp transmitted
      subst material
      have fresh := reactiveFreshSlot_spec view serial selected
      have unused : state.HandleUnused (who, .prepared serial) :=
        fun field accepted => valid.accepted_fixed field _ accepted fresh
      have vacant : state.accepted (.inr event) = none := by
        cases accepted : state.accepted (.inr event) with
        | none => rfl
        | some candidate =>
            exact (ready.1
              (valid.toAssociationInvariant.accepted_complete event candidate accepted)).elim
      change state.publicView.BindingIncludable runtime
        ⟨(who, execution.network.nextSerial who), .commitment event (who, .prepared serial)⟩ ∧ _
      refine ⟨?_, ?_⟩
      · simp only [PublicView.BindingIncludable, node]
        exact ⟨(state.publicView_eventReady event).mpr ready, timely,
          by trivial, by trivial, vacant, unused⟩
      · exact (runtime.reactiveApplication_packet_token leaks state who
          (execution.network.known who)
          ⟨⟨.commitment event (who, .prepared serial),
            match (cast (congrArg EventField.Action outputEq) action :
                PublicationResult (L.Val payload)) with
            | .failure => none
            | .success value => some ⟨payload, value⟩⟩, .none⟩).trans
          (state.publicView_tokenFor_of_ready _ event rfl ready)
  | resolve owner payload binding checks outputEq codeEq =>
      have ownerEq : owner = who := by
        have actorEq := congrArg EventCode.actor codeEq
        rw [EventCode.actor_cast outputEq (graph.nodes event)] at actorEq
        exact Option.some.inj (actorEq.symm.trans actor)
      subst owner
      simp only [reactiveDecision, node] at transmitted
      have normalized := runtime.reactiveResolutionSubmission_normal leaks state valid who event
        payload binding checks outputEq action
      change (reactiveResolutionPacket who event payload binding checks outputEq action view).map
        (fun packet => (disclosureSubmission packet).normalizeReactive who view []) =
          some material at transmitted
      change (reactiveResolutionPacket who event payload binding checks outputEq action view).map
        (fun packet => (disclosureSubmission packet).normalizeReactive who view []) =
          (reactiveResolutionPacket who event payload binding checks outputEq action view).map
            disclosureSubmission at normalized
      rw [normalized] at transmitted
      obtain ⟨packet, selected, same⟩ := Option.map_eq_some_iff.mp transmitted
      subst material
      have localResult : EventCode.resolveOutput? binding checks true view.observation.store =
          EventCode.resolveOutput? binding checks true state.config.store :=
        EventCode.resolveOutput?_playerStore binding checks state.config.store true
      cases discloses : cast (congrArg EventField.Action outputEq) action with
      | false => simp [reactiveResolutionPacket, discloses] at selected
      | true =>
          cases resolved : EventCode.resolveOutput? binding checks true state.config.store with
          | none => simp [reactiveResolutionPacket, discloses, localResult, resolved] at selected
          | some result =>
              cases result with
              | failure =>
                  simp [reactiveResolutionPacket, discloses, localResult, resolved] at selected
              | success value =>
                  obtain ⟨candidate, associated, owned, fixed, prescribed⟩ :=
                    runtime.reactiveResolutionPacket_provenance leaks state valid who event payload
                      binding checks outputEq action discloses value resolved
                  change reactiveResolutionPacket who event payload binding checks outputEq action
                    view = _ at prescribed
                  rw [prescribed] at selected
                  cases Option.some.inj selected
                  have emitted := runtime.windowOpening_packet leaks who event candidate
                    ⟨payload, value⟩ state (execution.network.known who) owned fixed
                  change runtime.freshServiceAcceptable state.publicView
                    ⟨(who, execution.network.nextSerial who),
                      (runtime.reactiveApplication leaks).packet state who
                        (execution.network.known who)
                        (disclosureSubmission (.opening event candidate ⟨payload, value⟩))⟩
                  rw [emitted, state.publicView_tokenFor_of_ready _ event rfl ready]
                  change runtime.freshServiceEnvelope state.publicView
                    ⟨(who, execution.network.nextSerial who),
                      ⟨.opening event candidate ⟨payload, value⟩,
                        some ⟨candidate, ⟨payload, value⟩⟩, some ⟨event⟩⟩⟩
                  apply (runtime.freshServiceEnvelope_opening_iff state.publicView
                    (who, execution.network.nextSerial who) event who payload binding checks
                      outputEq
                    codeEq node candidate ⟨payload, value⟩ (some ⟨candidate, ⟨payload, value⟩⟩)
                      _).mpr
                  refine ⟨(state.publicView_eventReady event).mpr ready, timely,
                    by simp only [certifiedOpening, decide_true], ?_, rfl, owned, associated,
                    rfl, rfl⟩
                  apply (state.publicView.openingGuardsAccepted_iff who event payload binding checks
                    outputEq codeEq node candidate ⟨payload, value⟩ _).mpr
                  refine ⟨value, rfl, ?_⟩
                  change GuardCheck.allAccepted? checks (graph.publicStore state.config.store)
                    (.success value) = some true
                  rw [GuardCheck.allAccepted?_publicStore]
                  exact EventCode.guards_pass_of_resolve_success binding checks true
                    state.config.store value resolved

/-- Actual supported prescribed responses inherit fresh-call acceptance from
their sampled ready owned event. No external packet-conformance promise is
needed, and the original intention remains explicit in the joint response. -/
theorem prescribedReactiveResponse_emitted_acceptable (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (WitnessedPacket graph))
    (execution : (runtime.reactiveApplication leaks).Execution)
    (valid : execution.application.BindingInvariant)
    (who : Player) (policy : graph.BehavioralPolicy who)
    (history : List (runtime.reactiveApplication leaks).PlayerEntry)
    (intentions : List (Option graph.Completion))
    (physical : (runtime.reactiveApplication leaks).Action) (remembered : graph.Completion)
    (supported : (physical, some remembered) ∈
      (runtime.prescribedReactiveResponse leaks who policy history intentions
        (execution.observe (runtime.reactiveApplication leaks) who)).support)
    (timely : execution.application.WithinDeadline runtime remembered.event)
    (material : WitnessedSubmission graph)
    (transmitted : physical.transmission = some material) :
    runtime.freshServiceAcceptable execution.application.publicView
      ⟨(who, execution.network.nextSerial who),
        material.emit ((runtime.reactiveApplication leaks).submit execution.application who
          material)
          who (execution.network.known who)⟩ := by
  unfold prescribedReactiveResponse at supported
  split at supported
  · simp at supported
  · rename_i event turn
    split at supported
    · simp at supported
    · split at supported
      · split at supported
        · rename_i ready
          split at supported
          · rename_i actor
            obtain ⟨choice, _, image⟩ := PMF.support_map .. ▸ supported
            have responseEq := congrArg Prod.fst image
            have intentionEq := Option.some.inj (congrArg Prod.snd image)
            dsimp only at responseEq intentionEq
            subst remembered
            apply runtime.reactiveDecision_emitted_acceptable leaks execution valid who event
              ((execution.application.publicView_eventReady event).mp ready) timely actor
              choice material
            exact (congrArg ReactiveApplication.Action.transmission responseEq).trans transmitted
          · simp at supported
        · simp at supported
      · simp at supported

end Vegas.EventGraphRuntime
