/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.Pending.ReactiveBoundedHandles
import Vegas.Pending.ReactiveCandidateBudget
import Vegas.Pending.ReactiveNormalPolicy
import Interaction.ReactiveMenuPolicy

/-! # Compiler coverage of finite response domains

Covering all binding and publication value types is a sufficient static
encoding condition. With at least one prepared serial per scheduler opportunity,
every compiled response is available at every legal decision history, including
histories generated by arbitrary earlier deviations. No response is truncated.
-/

noncomputable section

namespace Vegas.EventGraphRuntime.MessageBounds

open Interaction GameTheory.Math.Probability EventGraph

variable {Player : Type} [DecidableEq Player]
  {L : IExpr} [IExpr.ResultTypes L] {graph : Vegas.EventGraph Player L}
  (bounds : MessageBounds graph)

/-- A sufficient static domain condition, independent of source policies.
Private input and chance types need no additional wire choices unless an event
can bind or publish a value of that type. -/
def CoversOutputValues : Prop := ∀ event,
  match graph.outputLayout event with
  | .binding _ payload | .publication payload =>
      ∀ value : L.Val payload, (⟨payload, value⟩ : Raw L) ∈ bounds.values
  | .publicData _ | .privateInput _ _ => True

theorem resolutionPacket_allowed {owner : Player} (who : Player) (event : graph.EventId)
    (payload : L.Ty) (binding : FieldRef graph.layout (.binding owner payload))
    (checks : List (GuardCheck graph.layout payload))
    (outputEq : graph.outputLayout event = .publication payload)
    (choice : graph.Action event) (view : ReactivePlayerView graph)
    (values : ∀ value : L.Val payload, (⟨payload, value⟩ : Raw L) ∈ bounds.values)
    (handles : ∀ field candidate, view.publicView.accepted field = some candidate →
      bounds.AllowsHandle candidate) :
    bounds.AllowsPacket (reactiveResolutionPacket who event payload binding checks
      outputEq choice view) := by
  dsimp only [reactiveResolutionPacket]
  split
  · split
    · rename_i value resolved
      split
      · rename_i candidate accepted
        split
        · exact ⟨handles binding.field candidate accepted, values value⟩
        · trivial
      · trivial
    · trivial
    · trivial
  · trivial

variable [Fintype Player]

theorem silent_available (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (Payload graph)) (who : Player)
    (past : List (runtime.reactiveApplication leaks).PlayerEntry)
    (view : (runtime.reactiveApplication leaks).PlayerView) :
    (⟨none⟩ : (runtime.reactiveApplication leaks).Action) ∈
      (bounds.menu runtime leaks).actions who past view := by
  rw [bounds.menu_mem]
  exact ⟨trivial, rfl⟩

theorem reactiveDecision_available (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (Payload graph)) (who : Player)
    (past : List (runtime.reactiveApplication leaks).PlayerEntry)
    (view : (runtime.reactiveApplication leaks).PlayerView)
    (values : bounds.CoversOutputValues)
    (handles : ∀ field candidate, view.application.publicView.accepted field = some candidate →
      bounds.AllowsHandle candidate)
    (fresh : ∀ serial, reactiveFreshSlot view.application = some serial →
      serial < bounds.candidateCount) (event : graph.EventId) (choice : graph.Action event) :
    runtime.reactiveDecision leaks who event choice view.application ∈
      (bounds.menu runtime leaks).actions who past view := by
  rw [bounds.menu_mem]
  refine ⟨?_, runtime.reactiveDecision_normal leaks who past view event choice⟩
  cases node : nodeView graph event with
  | sample => simp only [reactiveDecision, node]
  | bind owner payload outputEq codeEq =>
      have typed := values event
      rw [outputEq] at typed
      cases selected : reactiveFreshSlot view.application with
      | none => simp only [reactiveDecision, node, selected, Option.map_none]
      | some serial =>
          simp only [reactiveDecision, node, selected, Option.map_some]
          refine ⟨fresh serial selected, ?_⟩
          change bounds.AllowsOpening
            (match (cast (congrArg EventField.Action outputEq) choice :
                PublicationResult (L.Val payload)) with
            | .failure => none
            | .success value => some ⟨payload, value⟩)
          split
          · trivial
          · exact typed _
  | resolve owner payload binding checks outputEq codeEq =>
      have typed := values event
      rw [outputEq] at typed
      simp only [reactiveDecision, node]
      exact ⟨bounds.resolutionPacket_allowed who event payload binding checks outputEq choice
        view.application typed handles, trivial⟩

private theorem prescribed_response_available (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (Payload graph)) (who : Player)
    (policy : graph.BehavioralPolicy who)
    (past : List (runtime.reactiveApplication leaks).PlayerEntry)
    (intentions : List (Option graph.Completion))
    (view : (runtime.reactiveApplication leaks).PlayerView)
    (decisions : ∀ event choice, runtime.reactiveDecision leaks who event choice view.application ∈
      (bounds.menu runtime leaks).actions who past view)
    (response : (runtime.reactiveApplication leaks).Action × Option graph.Completion)
    (supported : response ∈
      (runtime.prescribedReactiveResponse leaks who policy past intentions view).support) :
    response.1 ∈ (bounds.menu runtime leaks).actions who past view := by
  unfold prescribedReactiveResponse at supported
  split at supported
  · cases FinDist.mem_support_pure.mp supported
    exact bounds.silent_available runtime leaks who past view
  · split at supported
    · cases FinDist.mem_support_pure.mp supported
      exact bounds.silent_available runtime leaks who past view
    · split at supported
      · split at supported
        · split at supported
          · obtain ⟨choice, _, rfl⟩ := FinDist.support_map .. ▸ supported
            exact decisions _ choice
          · cases FinDist.mem_support_pure.mp supported
            exact bounds.silent_available runtime leaks who past view
        · cases FinDist.mem_support_pure.mp supported
          exact bounds.silent_available runtime leaks who past view
      · cases FinDist.mem_support_pure.mp supported
        exact bounds.silent_available runtime leaks who past view

private theorem recovery_response_available (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (Payload graph)) (who : Player)
    (policy : graph.BehavioralPolicy who)
    (past : List (runtime.reactiveApplication leaks).PlayerEntry)
    (intentions : List (Option graph.Completion))
    (view : (runtime.reactiveApplication leaks).PlayerView)
    (decisions : ∀ event choice, runtime.reactiveDecision leaks who event choice view.application ∈
      (bounds.menu runtime leaks).actions who past view)
    (response : (runtime.reactiveApplication leaks).Action × Option graph.Completion)
    (supported : response ∈
      (runtime.recoverReactiveResponse leaks who policy past intentions view).support) :
    response.1 ∈ (bounds.menu runtime leaks).actions who past view := by
  unfold recoverReactiveResponse at supported
  split at supported
  · cases FinDist.mem_support_pure.mp supported
    exact bounds.silent_available runtime leaks who past view
  · split at supported
    · split at supported
      · split at supported
        · obtain ⟨choice, _, rfl⟩ := FinDist.support_map .. ▸ supported
          exact decisions _ choice
        · cases FinDist.mem_support_pure.mp supported
          exact bounds.silent_available runtime leaks who past view
      · cases FinDist.mem_support_pure.mp supported
        exact bounds.silent_available runtime leaks who past view
    · cases FinDist.mem_support_pure.mp supported
      exact bounds.silent_available runtime leaks who past view

theorem compiled_response_available (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (Payload graph)) (who : Player)
    (policy : graph.BehavioralPolicy who)
    (past : List (runtime.reactiveApplication leaks).PlayerEntry)
    (view : (runtime.reactiveApplication leaks).PlayerView)
    (values : bounds.CoversOutputValues)
    (handles : ∀ field candidate, view.application.publicView.accepted field = some candidate →
      bounds.AllowsHandle candidate)
    (fresh : ∀ serial, reactiveFreshSlot view.application = some serial →
      serial < bounds.candidateCount)
    (response : (runtime.reactiveApplication leaks).Action)
    (supported : response ∈ (runtime.compileReactivePolicy leaks who policy past view).support) :
    response ∈ (bounds.menu runtime leaks).actions who past view := by
  have decisions :=
    bounds.reactiveDecision_available runtime leaks who past view values handles fresh
  unfold compileReactivePolicy ReactiveApplication.Policy.recover at supported
  split at supported
  · rw [prescribedReactivePolicy_apply] at supported
    obtain ⟨intentions, _, chosen⟩ := Set.mem_iUnion₂.mp (FinDist.support_bind .. ▸ supported)
    obtain ⟨response, selected, rfl⟩ := FinDist.support_map .. ▸ chosen
    exact prescribed_response_available bounds runtime leaks who policy past intentions view
      decisions response selected
  · rw [recoverReactivePolicy_apply] at supported
    obtain ⟨intentions, _, chosen⟩ := Set.mem_iUnion₂.mp (FinDist.support_bind .. ▸ supported)
    obtain ⟨response, selected, rfl⟩ := FinDist.support_map .. ▸ chosen
    exact recovery_response_available bounds runtime leaks who policy past intentions view
      decisions response selected

/-- Coverage holds at every legal decision, independently of how that history
was reached. The source policy and all earlier deviators are unrestricted. -/
theorem compiled_response_available_history (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (Payload graph))
    (inputs : FinDist graph.Inputs) (horizon : Nat)
    (scheduler : (runtime.reactiveApplication leaks).Scheduler)
    (values : bounds.CoversOutputValues) (capacity : horizon ≤ bounds.candidateCount)
    (control : (runtime.reactiveApplication leaks).Control)
    (trace : ((bounds.menu runtime leaks).protocol (inputs.map State.initial)
      horizon scheduler).Trace (some control)) (who : Player) (active : control.actor = some who)
    (policy : graph.BehavioralPolicy who) (response : (runtime.reactiveApplication leaks).Action)
    (supported : response ∈ (runtime.compileReactivePolicy leaks who policy
      (control.execution.recall who)
      (control.execution.observe (runtime.reactiveApplication leaks) who)).support) :
    response ∈ (bounds.menu runtime leaks).actions who (control.execution.recall who)
      (control.execution.observe (runtime.reactiveApplication leaks) who) := by
  have valid := bounds.executionHandles_history runtime leaks inputs horizon scheduler trace
  obtain ⟨serial, small, selected⟩ := runtime.reactiveFreshSlot_lt_horizon leaks inputs horizon
    scheduler control
    ((bounds.menu runtime leaks).toRawTrace (inputs.map State.initial) horizon scheduler trace)
    who active
  apply bounds.compiled_response_available runtime leaks who policy
    (control.execution.recall who)
    (control.execution.observe (runtime.reactiveApplication leaks) who) values valid.1 _
      response supported
  intro chosen found
  have same := Option.some.inj (found.symm.trans selected)
  subst chosen
  exact lt_of_lt_of_le small capacity

theorem compiledPolicy_admissible (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (Payload graph))
    (inputs : FinDist graph.Inputs) (horizon : Nat)
    (scheduler : (runtime.reactiveApplication leaks).Scheduler)
    (values : bounds.CoversOutputValues) (capacity : horizon ≤ bounds.candidateCount)
    (who : Player) (policy : graph.BehavioralPolicy who) :
    (bounds.menu runtime leaks).Admissible (inputs.map State.initial) horizon scheduler who
      (runtime.compileReactivePolicy leaks who policy) :=
  fun control trace active response supported =>
    bounds.compiled_response_available_history runtime leaks inputs horizon scheduler
      values capacity control trace who active policy response supported

/-- The finite-game compiler requires domain and capacity certificates. These
are model premises; no out-of-bounds response is substituted on a legal history. -/
def compileFinitePolicy (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (Payload graph))
    (inputs : FinDist graph.Inputs) (horizon : Nat)
    (scheduler : (runtime.reactiveApplication leaks).Scheduler)
    (values : bounds.CoversOutputValues) (capacity : horizon ≤ bounds.candidateCount)
    (who : Player) (policy : graph.BehavioralPolicy who) :
    ((bounds.menu runtime leaks).information (inputs.map State.initial)
      horizon scheduler).BehavioralPolicy who :=
  (bounds.menu runtime leaks).restrictPolicy (inputs.map State.initial) horizon scheduler who
    (runtime.compileReactivePolicy leaks who policy)
    (bounds.compiledPolicy_admissible runtime leaks inputs horizon scheduler
      values capacity who policy)

/-- All complete continuation histories agree with the actual reactive compiler,
from every legal finite-instance prefix, including genuinely off-path prefixes.
This is a representation theorem, not source-game correctness or optimality. -/
theorem compileFinitePolicy_run (runtime : EventGraphRuntime graph)
    (leaks : MessageNetwork.ObservationRule Player (Payload graph))
    (inputs : FinDist graph.Inputs) (horizon : Nat)
    (scheduler : (runtime.reactiveApplication leaks).Scheduler)
    (values : bounds.CoversOutputValues) (capacity : horizon ≤ bounds.candidateCount)
    (profile : graph.BehavioralProfile) (fuel : Nat)
    (history : ((bounds.menu runtime leaks).protocol (inputs.map State.initial)
      horizon scheduler).History) :
    (((bounds.menu runtime leaks).information (inputs.map State.initial)
      horizon scheduler).runBehavioralFrom
        (fun who => bounds.compileFinitePolicy runtime leaks inputs horizon scheduler
          values capacity who (profile who)) fuel history).map
      ((bounds.menu runtime leaks).toRawHistory (inputs.map State.initial) horizon scheduler) =
    ((runtime.reactiveApplication leaks).information (inputs.map State.initial)
      horizon scheduler).runBehavioralFrom
        (fun who => (runtime.reactiveApplication leaks).encodePolicy
          (runtime.compileReactivePolicy leaks who (profile who))) fuel
        ((bounds.menu runtime leaks).toRawHistory (inputs.map State.initial)
          horizon scheduler history) :=
  (bounds.menu runtime leaks).run_restrict (inputs.map State.initial) horizon scheduler
    (fun who => runtime.compileReactivePolicy leaks who (profile who))
    (fun who => bounds.compiledPolicy_admissible runtime leaks inputs horizon scheduler
      values capacity who (profile who)) fuel history

end Vegas.EventGraphRuntime.MessageBounds
