/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import Vegas.Examples.SelectiveAssociation.RestrictedAliceOptimality
import Vegas.Examples.SelectiveAssociation.RestrictedGuessOptimality
import Vegas.Examples.SelectiveAssociation.RestrictedBeliefs

/-! # All native information sites under the prescribed no-leak profile

The original service has two ambient response opportunities and six owned
event responses. These are all the decision information sites, including
histories generated by arbitrary earlier raw responses. The only posterior
premise needed by their incentive proofs is the guessing comparison.
-/

noncomputable section

namespace Vegas.Examples.SelectiveAssociation.Restricted

open Vegas Vegas.EventGraphRuntime Interaction GameTheory GameTheory.Protocol
open GameTheory.Math.Probability

theorem site_observation (who : Player) (site : model.InformationSite who) :
    ∃ past view, site.1 = some (past, view) := by
  obtain ⟨history, _, _⟩ := site.2
  have active := InformationModel.InformationSite.active model site history
  have observed := history.2
  rw [history_observe] at observed
  change app.actor history.1.state = some who at active
  cases stateEq : history.1.state with
  | none => rw [stateEq] at active; cases active
  | some control =>
      change history.1.state.bind ReactiveApplication.Control.actor = some who at active
      rw [stateEq] at active observed
      change control.actor = some who at active
      refine ⟨control.execution.recall who, control.execution.observe app who, ?_⟩
      simpa only [ReactiveApplication.observe, active, ↓reduceIte] using observed.symm

theorem site_turn_owner (who : Player) (past : List app.PlayerEntry)
    (event : nativeGraph.EventId) (turn : nativeTurnEvent? who past.length = some event) :
    who = nativeOwner event :=
  (nativeTurnEvent?_spec turn).1.symm

theorem site_ambient_owner (who : Player) (site : model.InformationSite who)
    (past : List app.PlayerEntry) (view : app.PlayerView)
    (observed : site.1 = some (past, view))
    (ambient : nativeTurnEvent? who past.length = none) : who = alice ∨ who = bob := by
  obtain ⟨history, _, _⟩ := site.2
  obtain ⟨control, same, active, recalled, _⟩ := information_control who past view
    ⟨history.1, history.2.trans observed⟩
  rcases history with ⟨⟨state, trace⟩, historyInfo⟩
  change state = some control at same
  subst state
  have noTurn : nativeTurnEvent? who (control.execution.recall who).length = none := by
    rw [recalled]
    exact ambient
  rcases prelude_position who control trace active noTurn with first | second
  · exact Or.inl first.1
  · exact Or.inr second.1

theorem prescribed_sequentiallyRational (assessment : model.BehavioralAssessment)
    (strategy : assessment.strategy = profile) (beliefs : GuessBeliefs assessment) :
    assessment.IsSequentiallyRationalFor fun who site =>
        assessment.truncatedContinuationContext site (fun history => nativeUtility who
            history.state) (2 * nativeHorizon + 1) := by
  intro who site
  obtain ⟨past, view, observed⟩ := site_observation who site
  cases turn : nativeTurnEvent? who past.length with
  | none =>
      rcases site_ambient_owner who site past view observed turn with rfl | rfl
      · exact alice_early_rational assessment strategy site past view observed (Or.inl turn)
      · exact bob_prelude_rational assessment strategy site past view observed turn
  | some event =>
      have owner := site_turn_owner who past event turn
      subst who
      fin_cases event
      · exact alice_early_rational assessment strategy site past view observed (Or.inr turn)
      · exact profile_guesser_rational assessment strategy carol (by decide) site past view
          observed turn (beliefs carol site past view observed (by decide) turn)
      · exact profile_guesser_rational assessment strategy bob (by decide) site past view
          observed turn (beliefs bob site past view observed (by decide) turn)
      · exact profile_opening_rational assessment strategy alice site past view observed turn
      · exact profile_opening_rational assessment strategy carol site past view observed turn
      · exact profile_opening_rational assessment strategy bob site past view observed turn

/-- A sequential equilibrium of the original bounded native game when its
passive observation rule always returns the empty set. The complete raw menus,
service calendar, inclusion selector and application are retained. -/
theorem exists_sequentialEquilibrium :
    ∃ assessment : model.BehavioralAssessment,
      assessment.strategy = profile ∧
      assessment.IsSequentialEquilibriumFor
        (menu.decisionInformationAntichain (PMF.pure nativeInitial) nativeHorizon scheduler)
        (fun who site => assessment.truncatedContinuationContext site
          (fun history => nativeUtility who history.state) (2 * nativeHorizon + 1)) := by
  obtain ⟨assessment, strategy, consistent, beliefs⟩ := exists_consistent_guess_assessment
  exact ⟨assessment, strategy,
    ⟨prescribed_sequentiallyRational assessment strategy beliefs, consistent⟩⟩

end Vegas.Examples.SelectiveAssociation.Restricted
