/-
Copyright (c) 2026 VegasCore contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: VegasCore contributors
-/

import Vegas.Compile.SealedSource

/-! # The strict sealed-message compiler edge

This is the baseline commitment compilation. It lowers every admitted graph
node to its own sealed-message rule: a commit node accepts an opaque handle and
a reveal node accepts a value-bearing opening for the previously accepted
handle. No adjacent commit/reveal pair is fused into a cleartext request.

The certificate is deliberately separate from the source language. It states
the conditions needed by this backend (currently a common value type and
unrestricted commit guards); it does not add a source construct or invent a
fallback. A later backend may strengthen the certificate or refine the ideal
service, but it must prove a new edge rather than silently changing this one.
-/

namespace Vegas

open EventGraph Interaction

variable {Player : Type} [DecidableEq Player] {L : IExpr}

structure SealedCompilation (source : WFProgram Player L) (ty : L.Ty) where
  supported : SealedFragment (ToEventGraph.compile source.core).graph ty

namespace SealedCompilation

variable {source : WFProgram Player L} {ty : L.Ty}

/-- The explicit sealed-message program generated by the strict backend. -/
noncomputable def program (compilation : SealedCompilation source ty) :
    SealedProgram Player := compilation.supported.compile

@[simp] theorem program_rules (compilation : SealedCompilation source ty) :
    compilation.program.rules =
      (ToEventGraph.compile source.core).graph.nodeOrder.map
        (fun node => Graph.sealedRule _ node) := rfl

/-- The strict backend has one runtime rule for every graph node. In
particular, a source commit followed by a reveal remains two protocol phases.
-/
theorem program_rule_count (compilation : SealedCompilation source ty) :
    compilation.program.rules.length =
      (ToEventGraph.compile source.core).graph.nodeCount := by
  simp [program, SealedFragment.compile, EventGraph.Graph.nodeOrder]

/-- The compiler edge is the checked end-to-end support theorem for this
backend. It includes arbitrary finite native actions, including malformed
traffic, replay, delivery, and inclusion; termination is intentionally a
separate premise because withholding is a runtime behavior.
-/
theorem run_source (compilation : SealedCompilation source ty)
    [DecidableEq (L.Val ty)]
    (actions : List (SealedProgram.Action Player (L.Val ty))) :
    ∃ cfg : Config (ToEventGraph.compile source.core).graph,
      (ToEventGraph.compile source.core).graph.decodeSealed ty
        (SealedProgram.run compilation.program
          (SealedProgram.State.empty Player (L.Val ty)) actions) = some cfg ∧
      Reachable (ToEventGraph.compile source.core).graph cfg ∧
      (Terminal (ToEventGraph.compile source.core).graph cfg →
        ∃ terminalEnv : VEnv L (ToEventGraph.compile source.core).terminalCtx,
          SmallStep.Star
            { ctx := source.core.Γ, env := source.core.env, cont := source.core.prog }
            { ctx := (ToEventGraph.compile source.core).terminalCtx,
              env := terminalEnv,
              cont := .ret (ToEventGraph.compile source.core).sourcePayoffs } ∧
          evalPayoffs? (ToEventGraph.compile source.core).payoffs cfg.store =
            some (evalPayoffs (ToEventGraph.compile source.core).sourcePayoffs terminalEnv) ∧
          ∀ {name bindTy}
            (h : VHasVar (ToEventGraph.compile source.core).terminalCtx name bindTy),
            Store.getAs cfg.store
              ((ToEventGraph.compile source.core).terminalState.fieldOf h) bindTy.base =
                some (terminalEnv.get h)) := by
  exact source.sealed_run_source ty compilation.supported actions

end SealedCompilation

end Vegas
