/-
Copyright (c) 2026 VegasCore contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: VegasCore contributors
-/

import Vegas.Compile.WindowedPrivacy

/-! # Paired focal policy inputs for the windowed runtime -/

noncomputable section

namespace Vegas

open EventGraph Interaction Interaction.MessageApplication GameTheory.Math.Probability

variable {P : Type} [DecidableEq P] {L : IExpr}

/-- Payloads generated by the window service to discharge an expired active
instruction. Their acceptance never depends on the envelope author. -/
def IsExpiryPayload : ApplicationImage.Payload P L → Prop
  | .expireChoice _ | .expireBinding _ | .conditional _ .expire => True
  | _ => False

theorem ApplicationImage.State.AgreesFor.handle_expiry
    {who : P} {left right : ApplicationImage.State P L}
    (h : left.AgreesFor who right) (image : ApplicationImage P L)
    (message : Message P (ApplicationImage.Payload P L))
    (hexpiry : IsExpiryPayload message.payload) :
    Option.Rel (ApplicationImage.State.AgreesFor who)
      (image.handle left message) (image.handle right message) := by
  rcases message with ⟨id, payload⟩
  cases payload with
  | malformed data | choice address typed | binding address handle => contradiction
  | expireChoice address =>
      cases hlookup : image.lookup address with
      | none => simp [ApplicationImage.handle, hlookup]
      | some instruction =>
          cases instruction with
          | sample code | bind code | conditional code => simp [ApplicationImage.handle, hlookup]
          | publicChoice code =>
              simp only [ApplicationImage.handle, hlookup, Option.bind_eq_bind,
                Option.bind_some, h.memory]
              cases code.resolveTimeout? right.memory with
              | none => exact .none
              | some value => exact .some (h.publish code value)
  | expireBinding address =>
      cases hlookup : image.lookup address with
      | none => simp [ApplicationImage.handle, hlookup]
      | some instruction =>
          cases instruction with
          | sample code | publicChoice code | conditional code =>
              simp [ApplicationImage.handle, hlookup]
          | bind code =>
              simp only [ApplicationImage.handle, hlookup, Option.bind_eq_bind,
                Option.bind_some, h.memory]
              cases code.resolveTimeout? right.memory with
              | none => exact .none
              | some value => exact .some (h.defaultBind code ⟨code.ty, value⟩)
  | conditional address payload =>
      cases payload <;> try contradiction
      cases hlookup : image.lookup address with
      | none => simp [ApplicationImage.handle, hlookup]
      | some instruction =>
          cases instruction with
          | sample code | bind code | publicChoice code => simp [ApplicationImage.handle, hlookup]
          | conditional code =>
              simp only [ApplicationImage.handle, hlookup, Option.bind_eq_bind,
                Option.bind_some, ConditionalCode.decode,
                ConditionalPublication.resolveDisposition?, ConditionalPublication.resolve?,
                ConditionalPublication.resolveDefault?, ConditionalPublication.ready,
                ConditionalPublication.defaultReady, h.memory]
              repeat' first | split | exact .none |
                exact .some (h.publishConditional code none)

namespace WindowedApplication

/-- The runtime state retained by a focal player's policy input. Other
principal histories, the native trace, and nonfocal private tables are
deliberately unconstrained. -/
structure PolicyAgreement (runtime : WindowedApplication P L) (who : P)
    (left right : runtime.application.PolicyExecution) : Prop where
  state : left.native.application.AgreesFor who right.native.application
  pool : left.native.pool = right.native.pool
  receipts : left.native.receipts = right.native.receipts
  history : left.principalHistory who = right.principalHistory who

namespace PolicyAgreement

variable {runtime : WindowedApplication P L} {who : P}
  {left right : runtime.application.PolicyExecution}

private theorem handle_expiry (h : left.native.application.AgreesFor who
    right.native.application) (message : Message P (ApplicationImage.Payload P L))
    (hexpiry : IsExpiryPayload message.payload) :
    Option.Rel (State.AgreesFor who)
      (runtime.handle left.native.application message)
      (runtime.handle right.native.application message) := by
  simp only [WindowedApplication.handle, h.active, h.base.memory]
  cases hactivation : right.native.application.active with
  | none => exact .none
  | some activation =>
      simp only [Option.bind_eq_bind, Option.bind_some]
      split
      · have hbase : Option.Rel (ApplicationImage.State.AgreesFor who)
            ((runtime.atOrigin activation.since).orderedApplication.handle
              left.native.application.base message)
            ((runtime.atOrigin activation.since).orderedApplication.handle
              right.native.application.base message) := by
          simp only [ApplicationImage.orderedApplication,
            MessageApplication.withAdmission]
          change Option.Rel (ApplicationImage.State.AgreesFor who)
            (if (runtime.atOrigin activation.since).admitsMessage
                left.native.application.base.memory message then
              (runtime.atOrigin activation.since).handle
                left.native.application.base message else none)
            (if (runtime.atOrigin activation.since).admitsMessage
                right.native.application.base.memory message then
              (runtime.atOrigin activation.since).handle
                right.native.application.base message else none)
          rw [h.base.memory]
          split
          · exact h.base.handle_expiry (runtime.atOrigin activation.since) message hexpiry
          · exact .none
        have hmap : ∀ (first second : Option (ApplicationImage.State P L)),
            Option.Rel (ApplicationImage.State.AgreesFor who) first second →
            Option.Rel (State.AgreesFor who)
              (first.bind fun next => some (runtime.advanceTo left.native.application next))
              (second.bind fun next =>
                some (runtime.advanceTo right.native.application next)) := by
          intro first second hpair
          cases hpair with
          | none => exact .none
          | some hnext => exact .some (h.advanceTo runtime hnext)
        exact hmap _ _ hbase
      · exact .none

/-- Related executions supply exactly the same native input to the focal raw
policy, without equating hidden application state. -/
theorem input_eq (h : PolicyAgreement runtime who left right) :
    (left.principalHistory who,
      State.observe runtime.application left.native who) =
    (right.principalHistory who,
      State.observe runtime.application right.native who) := by
  apply Prod.ext h.history
  simp only [State.observe, WindowedApplication.application, h.pool, h.receipts,
    h.state.base.memory, h.state.active]

/-- A fixed pure focal policy therefore chooses the same command in related
executions. -/
theorem pure_command_eq (h : PolicyAgreement runtime who left right)
    (command : List runtime.application.PlayerEntry → runtime.application.View →
      runtime.application.PlayerCommand) :
    command (left.principalHistory who) (State.observe runtime.application left.native who) =
      command (right.principalHistory who)
        (State.observe runtime.application right.native who) := by
  congr 1
  · exact congrArg Prod.fst h.input_eq
  · exact congrArg Prod.snd h.input_eq

/-- Executing the same focal command preserves the precise policy-input
relation. This includes replay: equal message pools select the same retained
original message, so rebroadcasting does not change its author. -/
theorem playerStep (h : PolicyAgreement runtime who left right)
    (command : runtime.application.PlayerCommand)
    (nextLeft nextRight : runtime.application.PolicyExecution)
    (hleft : nextLeft ∈ (runtime.application.playerStep who left command).support)
    (hright : nextRight ∈ (runtime.application.playerStep who right command).support) :
    PolicyAgreement runtime who nextLeft nextRight := by
  have hview : State.observe runtime.application left.native who =
      State.observe runtime.application right.native who :=
    congrArg Prod.snd h.input_eq
  cases command with
  | privateCommand privateCommand =>
      cases privateCommand with
      | register slot value =>
          simp only [MessageApplication.playerStep, MessageApplication.advance,
            PlayerCommand.toAction, MessageApplication.step, FinDist.pure_bind,
            FinDist.mem_support_pure] at hleft hright
          subst nextLeft
          subst nextRight
          refine ⟨⟨h.state.base.register slot value, h.state.active⟩,
            h.pool, h.receipts, ?_⟩
          simp only [if_pos, h.history, hview]
  | submit payload =>
      simp only [MessageApplication.playerStep, MessageApplication.advance,
        PlayerCommand.toAction, MessageApplication.step, FinDist.pure_bind,
        FinDist.mem_support_pure] at hleft hright
      subst nextLeft
      subst nextRight
      refine ⟨h.state, ?_, h.receipts, ?_⟩
      · simp only [MessagePool.submit, h.pool]
      · simp only [if_pos, h.history, hview]
  | replay id =>
      simp only [MessageApplication.playerStep, MessageApplication.advance,
        PlayerCommand.toAction, MessageApplication.step, FinDist.pure_bind,
        FinDist.mem_support_pure] at hleft hright
      subst nextLeft
      subst nextRight
      refine ⟨h.state, ?_, h.receipts, ?_⟩
      · rw [h.pool]
      · simp only [if_pos, h.history, hview]
  | wait =>
      simp only [MessageApplication.playerStep, MessageApplication.advance,
        PlayerCommand.toAction, FinDist.pure_bind, FinDist.mem_support_pure] at hleft hright
      subst nextLeft
      subst nextRight
      exact ⟨h.state, h.pool, h.receipts, by simp only [if_pos, h.history, hview]⟩

/-- A fixed pure raw focal policy selects the same command from the two actual
histories and observations. Consequently, any supported synchronized focal
invocations preserve policy agreement. The surrounding player rosters and
environment policies may differ away from the focal coordinate. -/
theorem invoke_player_pure (h : PolicyAgreement runtime who left right)
    (command : List runtime.application.PlayerEntry → runtime.application.View →
      runtime.application.PlayerCommand)
    (leftPlayers rightPlayers : P → runtime.application.PlayerPolicy)
    (leftEnvironment rightEnvironment : runtime.application.EnvironmentPolicy)
    (hleftPolicy : leftPlayers who = fun history view => FinDist.pure (command history view))
    (hrightPolicy : rightPlayers who = fun history view => FinDist.pure (command history view))
    (nextLeft nextRight : runtime.application.PolicyExecution)
    (hleft : nextLeft ∈
      (runtime.application.invoke leftPlayers leftEnvironment left (.player who)).support)
    (hright : nextRight ∈
      (runtime.application.invoke rightPlayers rightEnvironment right (.player who)).support) :
    PolicyAgreement runtime who nextLeft nextRight := by
  have hcommand := h.pure_command_eq command
  simp only [MessageApplication.invoke, hleftPolicy, hrightPolicy,
    FinDist.pure_bind] at hleft hright
  rw [hcommand] at hleft
  exact h.playerStep _ nextLeft nextRight hleft hright

/-- Different private registrations by another actor preserve the focal
policy input. Sent-history entries record the actual distinct commands only
for that other actor. -/
theorem playerStep_register_other (h : PolicyAgreement runtime who left right)
    (actor : P) (hother : actor ≠ who) (leftSlot rightSlot : Nat)
    (leftValue rightValue : TypedValue L)
    (nextLeft nextRight : runtime.application.PolicyExecution)
    (hleft : nextLeft ∈ (runtime.application.playerStep actor left
      (.privateCommand (.register leftSlot leftValue))).support)
    (hright : nextRight ∈ (runtime.application.playerStep actor right
      (.privateCommand (.register rightSlot rightValue))).support) :
    PolicyAgreement runtime who nextLeft nextRight := by
  simp only [MessageApplication.playerStep, MessageApplication.advance,
    PlayerCommand.toAction, MessageApplication.step, FinDist.pure_bind,
    FinDist.mem_support_pure] at hleft hright
  subst nextLeft
  subst nextRight
  refine ⟨⟨h.state.base.register_other actor hother leftSlot rightSlot
    leftValue rightValue, h.state.active⟩, h.pool, h.receipts, ?_⟩
  simp only [if_neg (Ne.symm hother), h.history]

/-- A nonfocal wait records only the other actor's local entry. -/
theorem playerStep_wait_other (h : PolicyAgreement runtime who left right)
    (actor : P) (hother : actor ≠ who)
    (nextLeft nextRight : runtime.application.PolicyExecution)
    (hleft : nextLeft ∈ (runtime.application.playerStep actor left .wait).support)
    (hright : nextRight ∈ (runtime.application.playerStep actor right .wait).support) :
    PolicyAgreement runtime who nextLeft nextRight := by
  simp only [MessageApplication.playerStep, MessageApplication.advance,
    PlayerCommand.toAction, FinDist.pure_bind, FinDist.mem_support_pure] at hleft hright
  subst nextLeft
  subst nextRight
  exact ⟨h.state, h.pool, h.receipts, by simp [Ne.symm hother, h.history]⟩

/-- Equal nonfocal submissions preserve the focal input. The message-pool
serial and payload are equal because the preceding pools agree; only the
other actor's local history is extended. -/
theorem playerStep_submit_other (h : PolicyAgreement runtime who left right)
    (actor : P) (hother : actor ≠ who) (payload : ApplicationImage.Payload P L)
    (nextLeft nextRight : runtime.application.PolicyExecution)
    (hleft : nextLeft ∈
      (runtime.application.playerStep actor left (.submit payload)).support)
    (hright : nextRight ∈
      (runtime.application.playerStep actor right (.submit payload)).support) :
    PolicyAgreement runtime who nextLeft nextRight := by
  simp only [MessageApplication.playerStep, MessageApplication.advance,
    PlayerCommand.toAction, MessageApplication.step, FinDist.pure_bind,
    FinDist.mem_support_pure] at hleft hright
  subst nextLeft
  subst nextRight
  refine ⟨h.state, ?_, h.receipts, ?_⟩
  · simp [MessagePool.submit, h.pool]
  · simp [Ne.symm hother, h.history]

/-- Synchronized environment waits preserve focal policy agreement. -/
theorem environmentPolicyStep_wait (h : PolicyAgreement runtime who left right)
    (nextLeft nextRight : runtime.application.PolicyExecution)
    (hleft : nextLeft ∈ (runtime.application.environmentPolicyStep left .wait).support)
    (hright : nextRight ∈ (runtime.application.environmentPolicyStep right .wait).support) :
    PolicyAgreement runtime who nextLeft nextRight := by
  simp only [MessageApplication.environmentPolicyStep, MessageApplication.advance,
    EnvironmentPolicyCommand.toAction, FinDist.pure_bind,
    FinDist.mem_support_pure] at hleft hright
  subst nextLeft
  subst nextRight
  exact ⟨h.state, h.pool, h.receipts, h.history⟩

/-- Advancing both window clocks by the same public value preserves focal
policy agreement. -/
theorem environmentPolicyStep_advance (h : PolicyAgreement runtime who left right)
    (clock : Nat) (nextLeft nextRight : runtime.application.PolicyExecution)
    (hleft : nextLeft ∈ (runtime.application.environmentPolicyStep left
      (.application (.advance clock))).support)
    (hright : nextRight ∈ (runtime.application.environmentPolicyStep right
      (.application (.advance clock))).support) :
    PolicyAgreement runtime who nextLeft nextRight := by
  simp only [MessageApplication.environmentPolicyStep, MessageApplication.advance,
    EnvironmentPolicyCommand.toAction, MessageApplication.step,
    WindowedApplication.application, WindowedApplication.environmentStep,
    FinDist.map_pure, FinDist.pure_bind,
    FinDist.mem_support_pure] at hleft hright
  subst nextLeft
  subst nextRight
  exact ⟨⟨h.state.base.advance clock, h.state.active⟩,
    h.pool, h.receipts, h.history⟩

/-- Actual inclusion of a focal-authored packet preserves enough private
state for the next focal decision, as well as equal public observations. -/
theorem environmentPolicyStep_include (h : PolicyAgreement runtime who left right)
    (id : MessageId P)
    (hauthor : ∀ message, left.native.pool.lookup id = some message → message.sender = who)
    (nextLeft nextRight : runtime.application.PolicyExecution)
    (hleft : nextLeft ∈
      (runtime.application.environmentPolicyStep left (.include id)).support)
    (hright : nextRight ∈
      (runtime.application.environmentPolicyStep right (.include id)).support) :
    PolicyAgreement runtime who nextLeft nextRight := by
  obtain ⟨hstate, hpool, hreceipts⟩ := runtime.includePending_agrees who left.native right.native
    h.state h.pool h.receipts id hauthor
  simp only [MessageApplication.environmentPolicyStep, MessageApplication.advance,
    EnvironmentPolicyCommand.toAction, MessageApplication.step, FinDist.pure_bind,
    FinDist.mem_support_pure] at hleft hright
  subst nextLeft
  subst nextRight
  exact ⟨hstate, hpool, hreceipts, h.history⟩

/-- Including an explicit expiry packet is permissionless: its original
sender need not be the focal principal. Equal pools select the same packet,
and expiry handling depends only on the related public application state. -/
theorem environmentPolicyStep_include_expiry
    (h : PolicyAgreement runtime who left right) (id : MessageId P)
    (hexpiry : ∀ message, left.native.pool.lookup id = some message →
      IsExpiryPayload message.payload)
    (nextLeft nextRight : runtime.application.PolicyExecution)
    (hleft : nextLeft ∈
      (runtime.application.environmentPolicyStep left (.include id)).support)
    (hright : nextRight ∈
      (runtime.application.environmentPolicyStep right (.include id)).support) :
    PolicyAgreement runtime who nextLeft nextRight := by
  have hincluded :
      let includedLeft := runtime.application.includePending left.native id
      let includedRight := runtime.application.includePending right.native id
      includedLeft.application.AgreesFor who includedRight.application ∧
        includedLeft.pool = includedRight.pool ∧
        includedLeft.receipts = includedRight.receipts := by
    cases hlookup : left.native.pool.lookup id with
    | none =>
        have hright : right.native.pool.lookup id = none := h.pool ▸ hlookup
        rw [MessageApplication.includePending_missing _ _ _ hlookup,
          MessageApplication.includePending_missing _ _ _ hright]
        exact ⟨h.state, h.pool, h.receipts⟩
    | some message =>
        have hright : right.native.pool.lookup id = some message := h.pool ▸ hlookup
        have hrelated := handle_expiry h.state message (hexpiry message hlookup)
        cases hleftHandle : runtime.handle left.native.application message with
        | none =>
            rw [hleftHandle] at hrelated
            have hrightHandle : runtime.handle right.native.application message = none := by
              generalize runtime.handle right.native.application message = result at hrelated ⊢
              cases hrelated
              rfl
            rw [MessageApplication.includePending_reject _ _ _ _ hlookup hleftHandle,
              MessageApplication.includePending_reject _ _ _ _ hright hrightHandle]
            exact ⟨h.state, by rw [h.pool], by rw [h.receipts]⟩
        | some afterLeft =>
            rw [hleftHandle] at hrelated
            cases hrightHandle : runtime.handle right.native.application message with
            | none => rw [hrightHandle] at hrelated; cases hrelated
            | some afterRight =>
                rw [hrightHandle] at hrelated
                have hnext : afterLeft.AgreesFor who afterRight := by
                  cases hrelated
                  assumption
                rw [MessageApplication.includePending_accept _ _ _ _ _ hlookup hleftHandle,
                  MessageApplication.includePending_accept _ _ _ _ _ hright hrightHandle]
                exact ⟨hnext, by rw [h.pool], by rw [h.receipts]⟩
  obtain ⟨hstate, hpool, hreceipts⟩ := hincluded
  simp only [MessageApplication.environmentPolicyStep, MessageApplication.advance,
    EnvironmentPolicyCommand.toAction, MessageApplication.step, FinDist.pure_bind,
    FinDist.mem_support_pure] at hleft hright
  subst nextLeft
  subst nextRight
  exact ⟨hstate, hpool, hreceipts, h.history⟩

end PolicyAgreement

/-- Different registrations by another actor preserve the focal native state
relation; the registered slots and values may differ on the two sides. -/
theorem State.AgreesFor.privateRegister_other
    {runtime : WindowedApplication P L} {who actor : P} (hne : actor ≠ who)
    {left right : State P L} (h : left.AgreesFor who right)
    (leftSlot rightSlot : Nat) (leftValue rightValue : TypedValue L) :
    (runtime.application.privateStep left actor (.register leftSlot leftValue)).AgreesFor who
      (runtime.application.privateStep right actor (.register rightSlot rightValue)) := by
  exact ⟨h.base.register_other actor hne leftSlot rightSlot leftValue rightValue, h.active⟩

end Vegas.WindowedApplication

/-- info: 'Vegas.WindowedApplication.PolicyAgreement.playerStep' depends on axioms:
[propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Vegas.WindowedApplication.PolicyAgreement.playerStep

/-- info: 'Vegas.WindowedApplication.PolicyAgreement.invoke_player_pure' depends on axioms:
[propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms Vegas.WindowedApplication.PolicyAgreement.invoke_player_pure
