/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import VegasTests.SelectiveAssociationRestrictedAliceOptimality
import VegasTests.SelectiveAssociationRestrictedGuessOptimality
import VegasTests.SelectiveAssociationRestrictedBeliefs

/-! # All native information sites under the prescribed no-leak profile

The original service has two ambient response opportunities and six owned
event responses. These are all the decision information sites, including
histories generated by arbitrary earlier raw responses. The only posterior
premise needed by their incentive proofs is the guessing comparison.
-/

noncomputable section

namespace VegasTests.SelectiveAssociation.Restricted

open Vegas Vegas.EventGraphRuntime Interaction GameTheory GameTheory.Protocol
open GameTheory.Math.Probability

theorem site_observation (who : Player) (site : model.InformationSite who) :
    ∃ past view, site.1 = some (past, view) := by
  obtain ⟨history, _, _⟩ := site.2
  have active := InformationModel.InformationSite.active model site history
  have observed := history.2
  rw [history_observe] at observed
  change app.actor history.1.state = some who at active
  cases stateEq : history.1.state with
  | none => rw [stateEq] at active; cases active
  | some control =>
      change history.1.state.bind ReactiveApplication.Control.actor = some who at active
      rw [stateEq] at active observed
      change control.actor = some who at active
      refine ⟨control.execution.recall who, control.execution.observe app who, ?_⟩
      simpa only [ReactiveApplication.observe, active, ↓reduceIte] using observed.symm

theorem site_granted_owner (who : Player) (site : model.InformationSite who)
    (past : List app.PlayerEntry) (view : app.PlayerView)
    (observed : site.1 = some (past, view)) (event : nativeGraph.EventId)
    (granted : view.application.publicView.serviceGrant = some event) :
    who = nativeOwner event := by
  obtain ⟨history, _, _⟩ := site.2
  obtain ⟨control, same, active, _, viewed⟩ := information_control who past view
    ⟨history.1, history.2.trans observed⟩
  rcases history with ⟨⟨state, trace⟩, historyInfo⟩
  change state = some control at same
  subst state
  have grant : control.execution.application.serviceGrant = some event := by
    rw [← viewed] at granted
    exact granted
  exact (native_decision_cursor (observation := leaks) event control trace who active grant).1

theorem site_ambient_owner (who : Player) (site : model.InformationSite who)
    (past : List app.PlayerEntry) (view : app.PlayerView)
    (observed : site.1 = some (past, view))
    (ambient : view.application.publicView.serviceGrant = none) : who = alice ∨ who = bob := by
  obtain ⟨history, _, _⟩ := site.2
  obtain ⟨control, same, active, _, viewed⟩ := information_control who past view
    ⟨history.1, history.2.trans observed⟩
  rcases history with ⟨⟨state, trace⟩, historyInfo⟩
  change state = some control at same
  subst state
  have noGrant : control.execution.application.serviceGrant = none := by
    rw [← viewed] at ambient
    exact ambient
  rcases prelude_position who control trace active noGrant with first | second
  · exact Or.inl first.1
  · exact Or.inr second.1

theorem prescribed_sequentiallyRational (assessment : model.BehavioralAssessment)
    (strategy : assessment.strategy = profile) (beliefs : GuessBeliefs assessment) :
    assessment.IsSequentiallyRationalWithin (fun who history => nativeUtility who history.state)
      (2 * nativeHorizon + 1) := by
  intro who site
  obtain ⟨past, view, observed⟩ := site_observation who site
  cases grant : view.application.publicView.serviceGrant with
  | none =>
      rcases site_ambient_owner who site past view observed grant with rfl | rfl
      · exact alice_early_rational assessment strategy site past view observed (Or.inl grant)
      · exact bob_prelude_rational assessment strategy site past view observed grant
  | some event =>
      have owner := site_granted_owner who site past view observed event grant
      subst who
      fin_cases event
      · exact alice_early_rational assessment strategy site past view observed (Or.inr grant)
      · exact profile_guesser_rational assessment strategy carol (by decide) site past view
          observed grant (beliefs carol site past view observed (by decide) grant)
      · exact profile_guesser_rational assessment strategy bob (by decide) site past view
          observed grant (beliefs bob site past view observed (by decide) grant)
      · exact profile_opening_rational assessment strategy alice site past view observed grant
      · exact profile_opening_rational assessment strategy carol site past view observed grant
      · exact profile_opening_rational assessment strategy bob site past view observed grant

/-- A sequential equilibrium of the original bounded native game when its
passive observation rule always returns the empty set. The complete raw menus,
service calendar, inclusion selector and application are retained. -/
theorem exists_sequentialEquilibrium :
    ∃ assessment : model.BehavioralAssessment,
      assessment.strategy = profile ∧
      assessment.IsSequentialEquilibriumFor
        (menu.decisionInformationAntichain (FinDist.pure nativeInitial) nativeHorizon scheduler)
        (fun who site => assessment.continuationContext site
          (fun history => nativeUtility who history.state) (2 * nativeHorizon + 1)) := by
  obtain ⟨assessment, strategy, consistent, beliefs⟩ := exists_consistent_guess_assessment
  exact ⟨assessment, strategy,
    ⟨prescribed_sequentiallyRational assessment strategy beliefs, consistent⟩⟩

end VegasTests.SelectiveAssociation.Restricted
