/- Copyright (c) 2026 VegasCore contributors. All rights reserved. -/

import GameTheory.Math.Probability.FinDist
import Mathlib.Analysis.Convex.Cone.InnerDual
import Mathlib.Analysis.InnerProductSpace.PiL2

/-! # Exact implication between finite-outcome incentive constraints

An incentive comparison orders two outcome laws. For every utility to respect
a target comparison whenever it respects all source comparisons, the target's
probability difference must belong to the smallest closed convex cone containing
the source differences. This criterion is necessary and sufficient. It need
not match either outcome law separately or normalize nonnegative coefficients.

The outcome carrier is finite. The family of comparisons can be infinite;
the criterion uses its closed cone and asserts no decision procedure.
-/

noncomputable section

namespace GameTheory

open Math.Probability
open scoped RealInnerProductSpace

universe u v

/-- Keeping a prescribed plan must be at least as good as its alternative. -/
structure IncentiveComparison (Outcome : Type u) where
  prescribed : FinDist Outcome
  alternative : FinDist Outcome

namespace IncentiveComparison

variable {Outcome : Type u}

def Holds (comparison : IncentiveComparison Outcome) (utility : Outcome → ℝ) : Prop :=
  comparison.alternative.expect utility ≤ comparison.prescribed.expect utility

variable [Fintype Outcome]

/-- Signed mass of keeping the prescribed plan rather than deviating. -/
def difference (comparison : IncentiveComparison Outcome) : EuclideanSpace ℝ Outcome :=
  WithLp.toLp 2 (fun outcome => comparison.prescribed.prob outcome -
    comparison.alternative.prob outcome)

theorem inner_difference (comparison : IncentiveComparison Outcome) (utility : Outcome → ℝ) :
    ⟪comparison.difference, WithLp.toLp 2 utility⟫ =
      comparison.prescribed.expect utility - comparison.alternative.expect utility := by
  simp only [difference, EuclideanSpace.inner_toLp_toLp, dotProduct, Pi.star_apply,
    star_trivial, FinDist.expect_eq_sum, mul_sub, Finset.sum_sub_distrib]
  congr 1 <;> apply Finset.sum_congr rfl <;> intro outcome _ <;> exact mul_comm _ _

theorem holds_iff_inner (comparison : IncentiveComparison Outcome) (utility : Outcome → ℝ) :
    comparison.Holds utility ↔ 0 ≤ ⟪comparison.difference, WithLp.toLp 2 utility⟫ := by
  rw [inner_difference]
  exact sub_nonneg.symm

variable {Index : Type v}

/-- The closed convex cone generated by all source incentive differences. -/
def cone (comparisons : Index → IncentiveComparison Outcome) :
    ProperCone ℝ (EuclideanSpace ℝ Outcome) :=
  ProperCone.innerDual (ProperCone.innerDual (Set.range (fun index =>
    (comparisons index).difference)) : Set (EuclideanSpace ℝ Outcome))

theorem difference_mem_cone (comparisons : Index → IncentiveComparison Outcome) (index : Index) :
    (comparisons index).difference ∈ cone comparisons := by
  intro utility nonnegative
  change 0 ≤ ⟪utility, (comparisons index).difference⟫
  rw [real_inner_comm]
  exact nonnegative ⟨index, rfl⟩

/-- This really is the least closed convex cone containing the comparisons. -/
theorem cone_le_iff (comparisons : Index → IncentiveComparison Outcome)
    (C : ProperCone ℝ (EuclideanSpace ℝ Outcome)) :
    cone comparisons ≤ C ↔ ∀ index, (comparisons index).difference ∈ C := by
  refine ⟨fun below index => below (difference_mem_cone comparisons index), ?_⟩
  intro contains
  have included : Set.range (fun index => (comparisons index).difference) ⊆ C := by
    rintro _ ⟨index, rfl⟩
    exact contains index
  have dual := ProperCone.innerDual_le_innerDual included
  have doubleDual := ProperCone.innerDual_le_innerDual dual
  simpa only [cone, ProperCone.innerDual_innerDual] using doubleDual

/-- Exact, utility-independent implication of one target incentive constraint. -/
theorem mem_cone_iff (comparisons : Index → IncentiveComparison Outcome)
    (target : IncentiveComparison Outcome) :
    target.difference ∈ cone comparisons ↔
      ∀ utility, (∀ index, (comparisons index).Holds utility) → target.Holds utility := by
  constructor
  · intro included utility respected
    rw [holds_iff_inner]
    rw [real_inner_comm]
    apply included
    rintro _ ⟨index, rfl⟩
    exact ((comparisons index).holds_iff_inner utility).mp (respected index)
  · intro preserves utility respected
    have each (index : Index) : (comparisons index).Holds (WithLp.ofLp utility) := by
      rw [holds_iff_inner]
      exact respected ⟨index, rfl⟩
    change 0 ≤ ⟪utility, target.difference⟫
    rw [real_inner_comm]
    exact (target.holds_iff_inner _).mp (preserves _ each)

/-- A failed cone inclusion supplies a separating utility. -/
theorem separating_utility (comparisons : Index → IncentiveComparison Outcome)
    (target : IncentiveComparison Outcome) (outside : target.difference ∉ cone comparisons) :
    ∃ utility, (∀ index, (comparisons index).Holds utility) ∧
      target.prescribed.expect utility < target.alternative.expect utility := by
  rw [mem_cone_iff] at outside
  push Not at outside
  simpa only [Holds, not_le] using outside

/-- Finite nonnegative combinations give checkable sufficient certificates;
the coefficients need not sum to one. -/
theorem mem_cone_of_nonnegative_combination
    (comparisons : Index → IncentiveComparison Outcome) (target : IncentiveComparison Outcome)
    {Terms : Type*} (terms : Finset Terms) (index : Terms → Index) (weight : Terms → ℝ)
    (nonnegative : ∀ term ∈ terms, 0 ≤ weight term)
    (represents : target.difference = ∑ term ∈ terms,
      weight term • (comparisons (index term)).difference) :
    target.difference ∈ cone comparisons := by
  rw [represents]
  apply (cone comparisons).sum_mem
  intro term member
  exact (cone comparisons).smul_mem (difference_mem_cone comparisons (index term))
    (nonnegative term member)

end IncentiveComparison
end GameTheory
